### ISSUE TITLE
Deploying the vote example fails on Windows

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1014]
### Current Behavior

Deploying the vote example on Windows fails with the following error:

```
Failed deploying service api (from module api). Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Error deploying api: BackOff - Back-off restarting failed container

━━━ Events ━━━
Pod api-5c48554bcc-pml4b: BackOff - Back-off restarting failed container
Deployment api: ScalingReplicaSet - Scaled up replica set api-7955dd5749 to 1
Deployment api: ScalingReplicaSet - Scaled down replica set api-5c48554bcc to 0pi:v-943e485be7"
Pod api-7955dd5749-zqlms: Scheduled - Successfully assigned garden-vote/api-7955dd5749-zqlms to gke-garden-dev-1-pool-1
-d55fb3d7-hp3l5749-zqlms: Created - Created container
Pod api-7955dd5749-zqlms: Pulling - pulling image "127.0.0.1:5000/garden-vote/api:v-943e485be7"
Pod api-7955dd5749-zqlms: Pulled - Successfully pulled image "127.0.0.1:5000/garden-vote/api:v-943e485be7"resent on mac
Pod api-7955dd5749-zqlms: Created - Created container
Pod api-7955dd5749-zqlms: Started - Started containerng failed container
Pod api-7955dd5749-zqlms: Pulled - Container image "127.0.0.1:5000/garden-vote/api:v-943e485be7" already present on mac
hinePod logs ━━━
Pod api-7955dd5749-zqlms: BackOff - Back-off restarting failed containermand for complete logs>
$ kubectl -n garden-vote --context=gke_garden-dev-200012_europe-west1-b_garden-dev-1 logs deployment/api
━━━ Pod logs ━━━
<Showing last 20 lines per pod in this Deployment. Run the following command for complete logs>
$ kubectl -n garden-vote --context=gke_garden-dev-200012_europe-west1-b_garden-dev-1 logs deployment/api
|* Restarting with stat
****** api-7955dd5749-zqlms ******
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat.0', port=80, debug=True, threaded=True)
Traceback (most recent call last):ite-packages/flask/app.py", line 990, in run
  File "app.py", line 52, in <module>tions)
    app.run(host='0.0.0.0', port=80, debug=True, threaded=True).py", line 1007, in run_simple
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)ges/werkzeug/_reloader.py", line 332, in run_with_reloader
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type) 176, in restart_with_reloader
  File "/usr/local/lib/python2.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())", line 172, in call
  File "/usr/local/lib/python2.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()y", line 1047, in _execute_child
  File "/usr/local/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)c format error
  File "/usr/local/lib/python2.7/subprocess.py", line 1047, in _execute_child━━━
    raise child_exception
OSError: [Errno 8] Exec format errorng status...
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

### Expected behavior

It should work.

### Reproducible example

Run `garden deploy` in the vote example on Windows.

### Your environment

Latest master, Windows 10.

**Comment by edvald** [comment]
@eysi09 is this still an issue?
