### ISSUE TITLE
Proxy fails with: TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#1088]
### Current Behavior

Sometimes when opening a port forward link, Garden crashes with:

```
/Users/eysi/code/garden-io/garden/garden-service/src/proxy.ts:156
      _remote.end()
              ^
TypeError: Cannot read property 'end' of undefined
    at Socket.local.on (/Users/eysi/code/garden-io/garden/garden-service/src/proxy.ts:156:15)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:610:12)
```

### Reproducible example

Run `garden dev` in `demo-project`. Open the port forward link in your browser, close it, open again, etc etc until it crashes.

**Comment by eysi09** [comment]
This also seems to happen when opening or closing the dashboard.
