### ISSUE TITLE
Unable to uninstall the demo project

### ISSUE THREAD

**Issue by kvokka** [garden-io/garden#1189]
## Bug

Should this plugin produce an error?

### Current Behavior

in the context of `garden/examples/demo-project`

```bash
$ garden dev # ctrl-c exit
$ local-kubernetes uninstall-garden-services

Removing cluster-wide services for local environment ⚙️

✔ providers                 → Getting status... → Done
 Deleting services...
    build-sync                → Deleting...
    default-backend           → Deleting...
    docker-registry           → Deleting...
    kubernetes-dashboard      → Deleting...
    docker-daemon             → Deleting...
    nfs-provisioner           → Deleting...
    ingress-controller        → Deleting...
    registry-proxy            → Deleting...
Command failed with exit code 1 (EPERM): /Users/mike/.garden/tools/helm/1c6ed8021f49d4ce/darwin-amd64/helm --tiller-namespace garden-system --k
ube-context minikube template --name garden-registry-proxy --namespace garden-system --values /Users/mike/tmp/garden/examples/demo-project/.gar
den/kubernetes.garden/build/registry-proxy/garden-values.yml /Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/regis
try-proxy

See error.log for detailed error message
```

```bash
# error.log


[2019-09-17T09:31:07.329Z] Error: Command failed with exit code 1 (EPERM): /Users/mike/.garden/tools/helm/1c6ed8021f49d4ce/darwin-amd64/helm --tiller-namespace garden-system --kube-context minikube template --name garden-registry-proxy --namespace garden-system --values /Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy/garden-values.yml /Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy
    at makeError (/snapshot/dist/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/snapshot/dist/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error Details:
command: >-
  /Users/mike/.garden/tools/helm/1c6ed8021f49d4ce/darwin-amd64/helm
  --tiller-namespace garden-system --kube-context minikube template --name
  garden-registry-proxy --namespace garden-system --values
  /Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy/garden-values.yml
  /Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy
exitCode: 1
exitCodeName: EPERM
stdout: ''
stderr: >-
  Error: no Chart.yaml exists in directory
  "/Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy"
all: >-
  Error: no Chart.yaml exists in directory
  "/Users/mike/tmp/garden/examples/demo-project/.garden/kubernetes.garden/build/registry-proxy"
failed: true
timedOut: false
isCanceled: false
killed: false
```

### Expected behavior

Something like `garden delete env`, or more appropriate error message or link to the docs.

### Your environment

`minikube`
1.3.1
`garden version`
0.10.9
`kubectl version`
1.15.2
`docker version`
2.1.0.2

**Comment by edvald** [comment]
It seems like the uninstall command has issues if you run it without having run the `cluster-init` command previously. We'll fix that. 

Thanks for the all the reports btw, we really appreciate it! :)
