### ISSUE TITLE
Self signed cert error when trying to initialize cluster-wide services

### ISSUE THREAD

**Issue by ajureeruja** [garden-io/garden#1217]
I am trying to evaluate Garden and have run into an error (message: self signed certificate in certificate chain) when trying to initialize cluster-wide services.  Is there a way to configure Garden to trust a self signed root ca?

**Comment by eysi09** [comment]
Hi @ajureeruja 

Sorry for the late reply. Would you mind sharing the entire error message and the contents of `error.log`? 

cc @edvald.

**Comment by ajureeruja** [comment]
Here is the cli output.

```
~/tmp/remote-k8s  garden --env=remote plugins kubernetes cluster-init                                                                                                                                                                 ✔ Initializing/updating cluster-wide services for remote environment

 providers                 → Getting status...
   ℹ Fetching kubectl...

Failed resolving provider kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Failed resolving one or more provider configurations:
- kubernetes: Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.

See error.log for detailed error message
```

Here is the contents of the error.log.

```
[2019-09-20T14:13:14.782Z] Error: Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.
    at Object.<anonymous> (/snapshot/dist/build/src/plugins/kubernetes/namespace.js:0)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/dist/build/src/plugins/kubernetes/namespace.js:0)
Error Details:
providerConfig:
  name: kubernetes
  context: test
  defaultHostname: <redacted>.com
  forceSsl: false
  tlsCertificates:
    - name: garden-tls
      secretRef:
        name: garden-tls
        namespace: default
  buildMode: cluster-docker
  environments:
    - remote
  imagePullSecrets: []
  resources:
    builder:
      limits:
        cpu: 4000
        memory: 8192
      requests:
        cpu: 200
        memory: 512
    registry:
      limits:
        cpu: 2000
        memory: 4096
      requests:
        cpu: 200
        memory: 512
    sync:
      limits:
        cpu: 500
        memory: 512
      requests:
        cpu: 100
        memory: 64
  storage:
    builder:
      size: 20480
      storageClass: null
    registry:
      size: 20480
      storageClass: null
    sync:
      size: 10240
      storageClass: null
  ingressHttpPort: 80
  ingressHttpsPort: 443
  setupIngressController: false
  path: /home/<redacted>/tmp/remote-k8s
  namespace: remote-example
  deploymentRegistry:
    hostname: '127.0.0.1:5000'
    namespace: remote-example
message: self signed certificate in certificate chain


[2019-09-20T14:13:14.806Z] Error: Failed resolving one or more provider configurations:
- kubernetes: Unable to connect to Kubernetes cluster. Please make sure it is running, reachable and that you have the right context configured.
    at Garden.<anonymous> (/snapshot/dist/build/src/garden.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/dist/build/src/garden.js:0)
Error Details:
rawConfigs:
  - name: exec
  - name: container
  - name: kubernetes
    context: test
    defaultHostname: <redacted>.com
    forceSsl: false
    tlsCertificates:
      - name: garden-tls
        secretRef:
          name: garden-tls
          namespace: default
    buildMode: cluster-docker
    environments:
      - remote
taskResults:
  resolve-provider.exec:
    type: resolve-provider
    key: resolve-provider.exec
    name: exec
    description: resolving provider exec
    output:
      name: exec
      dependencies: []
      moduleConfigs: []
      config:
        name: exec
        path: /home/<redacted>/tmp/remote-k8s
      status:
        ready: true
        outputs: {}
    dependencyResults: {}
  resolve-provider.container:
    type: resolve-provider
    key: resolve-provider.container
    name: container
    description: resolving provider container
    output:
      name: container
      dependencies: []
      moduleConfigs: []
      config:
        name: container
        path: /home/<redacted>/tmp/remote-k8s
      status:
        ready: true
        outputs: {}
    dependencyResults: {}
  resolve-provider.kubernetes:
    type: resolve-provider
    description: resolving provider kubernetes
    key: resolve-provider.kubernetes
    name: kubernetes
    error:
      detail:
        providerConfig:
          name: kubernetes
          context: test
          defaultHostname: <redacted>.com
          forceSsl: false
          tlsCertificates:
            - name: garden-tls
              secretRef:
                name: garden-tls
                namespace: default
          buildMode: cluster-docker
          environments:
            - remote
          imagePullSecrets: []
          resources:
            builder:
              limits:
                cpu: 4000
                memory: 8192
              requests:
                cpu: 200
                memory: 512
            registry:
              limits:
                cpu: 2000
                memory: 4096
              requests:
                cpu: 200
                memory: 512
            sync:
              limits:
                cpu: 500
                memory: 512
              requests:
                cpu: 100
                memory: 64
          storage:
            builder:
              size: 20480
              storageClass: null
            registry:
              size: 20480
              storageClass: null
            sync:
              size: 10240
              storageClass: null
          _systemServices:
            - build-sync
            - docker-registry
            - registry-proxy
            - docker-daemon
            - nfs-provisioner
          ingressHttpPort: 80
          ingressHttpsPort: 443
          setupIngressController: false
          path: /home/redacted>/tmp/remote-k8s
          namespace: remote-example
          deploymentRegistry:
            hostname: '127.0.0.1:5000'
            namespace: remote-example
        message: self signed certificate in certificate chain
      type: deployment
messages:
  - >-
    - kubernetes: Unable to connect to Kubernetes cluster. Please make sure it
    is running, reachable and that you have the right context configured.
```

**Comment by edvald** [comment]
Hmm, interesting. I'd have to dig into the behavior of the underlying tools/libraries (e.g. Node.js, kubectl etc.) to see how they can be configured.

A quick search turns up the following for Node.js: `set NODE_EXTRA_CA_CERTS=/path/to/your/cert.pem`.

Can you try that to see if you get further? I suspect there may be one or two other such settings we need to find, but this one should cover the Garden code itself, and the API libraries we use.

**Comment by edvald** [comment]
Once we solve this, we'll make sure to document it.

**Comment by ajureeruja** [comment]
I exported that variable and pointed it to the tls-ca-bundle.pem which contains the root ca cert and it is still giving me the above error.

**Comment by edvald** [comment]
Hmm ok. There are probably multiple moving parts here, and this is unfortunately not something we're well equipped to test ourselves. We do have instructions on how to use SOCKS proxies, is that an option to connect outside your firewall? https://docs.garden.io/basics/installation#using-garden-with-proxies

**Comment by ajureeruja** [comment]
Unfortunately that is not an option.

**Comment by ajureeruja** [comment]
Actually disregard, setting that environmental variable did get it to start deploying pods to the cluster.  It error-ed out while trying to deploy docker-registry and docker-daemon.  I'm not sure if we are completely passed the original issue and into a completely separate issue.  Here is the error log.

```

[2019-09-24T17:45:49.867Z] Error: kubernetes: 2 errors occurred when configuring environment
    at Object.<anonymous> (/snapshot/dist/build/src/plugins/kubernetes/system.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/dist/build/src/plugins/kubernetes/system.js:0)
Error Details:
results:
  taskResults:
    build.build-sync:
      type: build
      key: build.build-sync
      name: build-sync
      description: building build-sync
      output:
        fresh: true
      dependencyResults: {}
    build.registry-proxy:
      type: build
      key: build.registry-proxy
      name: registry-proxy
      description: building registry-proxy
      output:
        fresh: true
      dependencyResults: {}
    build.docker-daemon:
      type: build
      key: build.docker-daemon
      name: docker-daemon
      description: building docker-daemon
      output:
        fresh: true
      dependencyResults: {}
    get-service-status.registry-proxy:
      type: get-service-status
      key: get-service-status.registry-proxy
      name: registry-proxy
      description: >-
        getting status for service 'registry-proxy' (from module
        'registry-proxy')
      output:
        forwardablePorts: []
        state: missing
        detail:
          remoteObjects: []
      dependencyResults: {}
    build.docker-registry:
      type: build
      key: build.docker-registry
      name: docker-registry
      description: building docker-registry
      output:
        fresh: true
      dependencyResults: {}
    build.nfs-provisioner:
      type: build
      key: build.nfs-provisioner
      name: nfs-provisioner
      description: building nfs-provisioner
      output:
        fresh: true
      dependencyResults: {}
    get-service-status.nfs-provisioner:
      type: get-service-status
      key: get-service-status.nfs-provisioner
      name: nfs-provisioner
      description: >-
        getting status for service 'nfs-provisioner' (from module
        'nfs-provisioner')
      output:
        forwardablePorts: []
        state: missing
        detail:
          remoteObjects: []
      dependencyResults: {}
    get-service-status.docker-registry:
      type: get-service-status
      key: get-service-status.docker-registry
      name: docker-registry
      description: >-
        getting status for service 'docker-registry' (from module
        'docker-registry')
      output:
        forwardablePorts: []
        state: missing
        detail:
          remoteObjects: []
      dependencyResults: {}
    get-service-status.build-sync:
      type: get-service-status
      key: get-service-status.build-sync
      name: build-sync
      description: getting status for service 'build-sync' (from module 'build-sync')
      output:
        forwardablePorts: []
        state: missing
        detail:
          remoteObjects: []
      dependencyResults:
        get-service-status.nfs-provisioner:
          type: get-service-status
          key: get-service-status.nfs-provisioner
          name: nfs-provisioner
          description: >-
            getting status for service 'nfs-provisioner' (from module
            'nfs-provisioner')
          output:
            forwardablePorts: []
            state: missing
            detail:
              remoteObjects: []
          dependencyResults: {}
    get-service-status.docker-daemon:
      type: get-service-status
      key: get-service-status.docker-daemon
      name: docker-daemon
      description: getting status for service 'docker-daemon' (from module 'docker-daemon')
      output:
        forwardablePorts: []
        state: missing
        detail:
          remoteObjects: []
      dependencyResults:
        get-service-status.build-sync:
          type: get-service-status
          key: get-service-status.build-sync
          name: build-sync
          description: getting status for service 'build-sync' (from module 'build-sync')
          output:
            forwardablePorts: []
            state: missing
            detail:
              remoteObjects: []
          dependencyResults:
            get-service-status.nfs-provisioner:
              type: get-service-status
              key: get-service-status.nfs-provisioner
              name: nfs-provisioner
              description: >-
                getting status for service 'nfs-provisioner' (from module
                'nfs-provisioner')
              output:
                forwardablePorts: []
                state: missing
                detail:
                  remoteObjects: []
              dependencyResults: {}
    deploy.registry-proxy:
      type: deploy
      key: deploy.registry-proxy
      name: registry-proxy
      description: deploying service 'registry-proxy' (from module 'registry-proxy')
      output:
        forwardablePorts: []
        state: ready
        version: v-1713ebf8fe
      dependencyResults:
        get-service-status.registry-proxy:
          type: get-service-status
          key: get-service-status.registry-proxy
          name: registry-proxy
          description: >-
            getting status for service 'registry-proxy' (from module
            'registry-proxy')
          output:
            forwardablePorts: []
            state: missing
            detail:
              remoteObjects: []
          dependencyResults: {}
        build.registry-proxy:
          type: build
          key: build.registry-proxy
          name: registry-proxy
          description: building registry-proxy
          output:
            fresh: true
          dependencyResults: {}
    deploy.nfs-provisioner:
      type: deploy
      key: deploy.nfs-provisioner
      name: nfs-provisioner
      description: deploying service 'nfs-provisioner' (from module 'nfs-provisioner')
      output:
        forwardablePorts:
          - name: nfs
            protocol: TCP
            targetHostname: garden-nfs-provisioner
            targetPort: 2049
          - name: mountd
            protocol: TCP
            targetHostname: garden-nfs-provisioner
            targetPort: 20048
          - name: rpcbind-tcp
            protocol: TCP
            targetHostname: garden-nfs-provisioner
            targetPort: 51413
          - name: rpcbind-udp
            protocol: TCP
            targetHostname: garden-nfs-provisioner
            targetPort: 51413
        state: ready
        version: v-10338379e3
      dependencyResults:
        get-service-status.nfs-provisioner:
          type: get-service-status
          key: get-service-status.nfs-provisioner
          name: nfs-provisioner
          description: >-
            getting status for service 'nfs-provisioner' (from module
            'nfs-provisioner')
          output:
            forwardablePorts: []
            state: missing
            detail:
              remoteObjects: []
          dependencyResults: {}
        build.nfs-provisioner:
          type: build
          key: build.nfs-provisioner
          name: nfs-provisioner
          description: building nfs-provisioner
          output:
            fresh: true
          dependencyResults: {}
    deploy.build-sync:
      type: deploy
      key: deploy.build-sync
      name: build-sync
      description: deploying service 'build-sync' (from module 'build-sync')
      output:
        forwardablePorts: []
        state: ready
        version: v-21e17f336a
      dependencyResults:
        deploy.nfs-provisioner:
          type: deploy
          key: deploy.nfs-provisioner
          name: nfs-provisioner
          description: deploying service 'nfs-provisioner' (from module 'nfs-provisioner')
          output:
            forwardablePorts:
              - name: nfs
                protocol: TCP
                targetHostname: garden-nfs-provisioner
                targetPort: 2049
              - name: mountd
                protocol: TCP
                targetHostname: garden-nfs-provisioner
                targetPort: 20048
              - name: rpcbind-tcp
                protocol: TCP
                targetHostname: garden-nfs-provisioner
                targetPort: 51413
              - name: rpcbind-udp
                protocol: TCP
                targetHostname: garden-nfs-provisioner
                targetPort: 51413
            state: ready
            version: v-10338379e3
          dependencyResults:
            get-service-status.nfs-provisioner:
              type: get-service-status
              key: get-service-status.nfs-provisioner
              name: nfs-provisioner
              description: >-
                getting status for service 'nfs-provisioner' (from module
                'nfs-provisioner')
              output:
                forwardablePorts: []
                state: missing
                detail:
                  remoteObjects: []
              dependencyResults: {}
            build.nfs-provisioner:
              type: build
              key: build.nfs-provisioner
              name: nfs-provisioner
              description: building nfs-provisioner
              output:
                fresh: true
              dependencyResults: {}
        get-service-status.build-sync:
          type: get-service-status
          key: get-service-status.build-sync
          name: build-sync
          description: getting status for service 'build-sync' (from module 'build-sync')
          output:
            forwardablePorts: []
            state: missing
            detail:
              remoteObjects: []
          dependencyResults:
            get-service-status.nfs-provisioner:
              type: get-service-status
              key: get-service-status.nfs-provisioner
              name: nfs-provisioner
              description: >-
                getting status for service 'nfs-provisioner' (from module
                'nfs-provisioner')
              output:
                forwardablePorts: []
                state: missing
                detail:
                  remoteObjects: []
              dependencyResults: {}
        build.build-sync:
          type: build
          key: build.build-sync
          name: build-sync
          description: building build-sync
          output:
            fresh: true
          dependencyResults: {}
    deploy.docker-registry:
      type: deploy
      description: deploying service 'docker-registry' (from module 'docker-registry')
      key: deploy.docker-registry
      name: docker-registry
      error:
        command: >-
          /home/<redacted>/.garden/tools/helm/cc4f4840be03cb72/linux-amd64/helm
          --tiller-namespace garden-system --kube-context <redacted> install
          /home/<redacted>/tmp/remote-k8s/.garden/kubernetes.garden/build/docker-registry/docker-registry
          --name garden-docker-registry --namespace garden-system --values
          /home/<redacted>/tmp/remote-k8s/.garden/kubernetes.garden/build/docker-registry/docker-registry/garden-values.yml
          --atomic --timeout 600 --replace
        exitCode: 1
        exitCodeName: EPERM
        stdout: >-
          INSTALL FAILED

          PURGING CHART

          Error: release garden-docker-registry failed: timed out waiting for
          the condition

          Successfully purged a chart!
        stderr: >-
          Error: release garden-docker-registry failed: timed out waiting for
          the condition
        all: >-
          INSTALL FAILED

          PURGING CHART

          Error: release garden-docker-registry failed: timed out waiting for
          the condition

          Successfully purged a chart!

          Error: release garden-docker-registry failed: timed out waiting for
          the condition
        failed: true
        timedOut: false
        isCanceled: false
        killed: false
    deploy.docker-daemon:
      type: deploy
      description: deploying service 'docker-daemon' (from module 'docker-daemon')
      key: deploy.docker-daemon
      name: docker-daemon
      error:
        command: >-
          /home/<redacted>/.garden/tools/helm/cc4f4840be03cb72/linux-amd64/helm
          --tiller-namespace garden-system --kube-context <redacted> install
          /home/<redacted>/tmp/remote-k8s/.garden/kubernetes.garden/build/docker-daemon
          --name garden-docker-daemon --namespace garden-system --values
          /home/<redacted>/tmp/remote-k8s/.garden/kubernetes.garden/build/docker-daemon/garden-values.yml
          --atomic --timeout 600 --replace
        exitCode: 1
        exitCodeName: EPERM
        stdout: >-
          INSTALL FAILED

          PURGING CHART

          Error: release garden-docker-daemon failed: timed out waiting for the
          condition

          Successfully purged a chart!
        stderr: >-
          Error: release garden-docker-daemon failed: timed out waiting for the
          condition
        all: >-
          INSTALL FAILED

          PURGING CHART

          Error: release garden-docker-daemon failed: timed out waiting for the
          condition

          Successfully purged a chart!

          Error: release garden-docker-daemon failed: timed out waiting for the
          condition
        failed: true
        timedOut: false
        isCanceled: false
        killed: false
  restartRequired: false
```

**Comment by edvald** [comment]
Ah, that's progress at least! Not entirely sure why Helm would be timing out there though. Does Helm work standalone? You could copy the (non-redacted) command in the log to see if the command works as it should. You might also try the same command without the `--atomic` flag, so that the resources remain in the `garden-system` namespace. 

If it's not something relating to connectivity to the cluster via the `helm` CLI I'm guessing either Pods or persistent volumes are not starting, but logs and resources could help shed light on it.
Anything particular about the cluster setup perhaps? Is it deployed within your own data center?

**Comment by ajureeruja** [comment]
It looks like the both docker-daemon and docker-registry is stuck on a pending pvc.  However, garden-build's pvc is Bound.  Looking at the yaml for the pvcs that are pending compared to the bound one shows that storageClassName is missing from the pending ones.  The garden-build's pvc has storageClassName set to garden-system-nfs.

**Comment by edvald** [comment]
Ah, then it could be that the cluster doesn't have a default storage class set. You can either set a default storage class, or explicitly set the storage class (see https://docs.garden.io/reference/providers/kubernetes#providers-storage-builder-storageclass and https://docs.garden.io/reference/providers/kubernetes#providers-storage-registry-storageclass).

We should add some code to detect that on initialization.

**Comment by ajureeruja** [comment]
Ok, little by little we are progressing.  Setting the default SC got past the last issue.  Just ran into another x509: certificate signed by unknown authority error while deploying the remote-k8s project.

cli output:
```
 garden --env=remote deploy                                                                                                                                                                             ✔ Deploy

✔ providers                 → Getting status... → Done
✖ node-service              → Building image node-service:v-29d3eb4e86...
✖ go-service                → Building image go-service:v-0778bf4835...

Failed building node-service. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command failed with exit code 1 (EPERM): /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted> --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build -t 127.0.0.1:5000/remote-example/node-service:v-29d3eb4e86 -f /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/Dockerfile /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


Failed building go-service. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Command failed with exit code 1 (EPERM): /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted> --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build -t 127.0.0.1:5000/remote-example/go-service:v-0778bf4835 -f /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/Dockerfile /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

(node:28707) Warning: Ignoring extra certs from `/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem`, load failed: error:0B07C065:x509 certificate routines:X509_STORE_add_cert:cert already in hash table

2 deploy task(s) failed!

See error.log for detailed error message
```

error.log output:
```

[2019-09-24T20:22:20.264Z] Error: Command failed with exit code 1 (EPERM): /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted> --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build -t 127.0.0.1:5000/remote-example/node-service:v-29d3eb4e86 -f /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/Dockerfile /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/
    at makeError (/snapshot/dist/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/snapshot/dist/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error Details:
command: >-
  /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted>
  --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c
  docker-daemon -- docker build -t
  127.0.0.1:5000/remote-example/node-service:v-29d3eb4e86 -f
  /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/Dockerfile
  /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/
exitCode: 1
exitCodeName: EPERM
stdout: "Sending build context to Docker daemon  8.192kB\r\r\nStep 1/8 : FROM node:9-alpine"
stderr: >-
  Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown
  authority

  command terminated with exit code 1
all: "Sending build context to Docker daemon  8.192kB\r\r\nStep 1/8 : FROM node:9-alpine\nGet https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\ncommand terminated with exit code 1"
failed: true
timedOut: false
isCanceled: false
killed: false


[2019-09-24T20:22:20.731Z] Error: Command failed with exit code 1 (EPERM): /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted> --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build -t 127.0.0.1:5000/remote-example/go-service:v-0778bf4835 -f /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/Dockerfile /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/
    at makeError (/snapshot/dist/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/snapshot/dist/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error Details:
command: >-
  /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl --context=<redacted>
  --namespace=garden-system exec -i garden-docker-daemon-86b7ffb9df-28mck -c
  docker-daemon -- docker build -t
  127.0.0.1:5000/remote-example/go-service:v-0778bf4835 -f
  /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/Dockerfile
  /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/
exitCode: 1
exitCodeName: EPERM
stdout: "Sending build context to Docker daemon  5.632kB\r\r\nStep 1/9 : FROM golang:1.8.3-alpine"
stderr: >-
  Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown
  authority

  command terminated with exit code 1
all: "Sending build context to Docker daemon  5.632kB\r\r\nStep 1/9 : FROM golang:1.8.3-alpine\nGet https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\ncommand terminated with exit code 1"
failed: true
timedOut: false
isCanceled: false
killed: false


[2019-09-24T20:22:20.764Z] Error: 2 deploy task(s) failed!
    at Object.<anonymous> (/snapshot/dist/build/src/commands/base.js:0)
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/dist/build/src/commands/base.js:0)
    at new Promise (<anonymous>)
    at __awaiter (/snapshot/dist/build/src/commands/base.js:0)
    at Object.handleTaskResults (/snapshot/dist/build/src/commands/base.js:0)
    at DeployCommand.<anonymous> (/snapshot/dist/build/src/commands/deploy.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/dist/build/src/commands/deploy.js:0)
Error Details:
results:
  taskResults:
    get-service-status.go-service:
      type: get-service-status
      key: get-service-status.go-service
      name: go-service
      description: getting status for service 'go-service' (from module 'go-service')
      output:
        forwardablePorts:
          - name: http
            protocol: TCP
            targetPort: 80
        ingresses:
          - hostname: <redacted>.com
            path: /
            port: 443
            protocol: https
        state: missing
        detail:
          remoteObjects: []
      dependencyResults: {}
    get-service-status.node-service:
      type: get-service-status
      key: get-service-status.node-service
      name: node-service
      description: getting status for service 'node-service' (from module 'node-service')
      output:
        forwardablePorts:
          - name: http
            protocol: TCP
            targetPort: 8080
        ingresses:
          - hostname: <redacted>.com
            path: /hello
            port: 443
            protocol: https
          - hostname: <redacted>.com
            path: /call-go-service
            port: 443
            protocol: https
        state: missing
        detail:
          remoteObjects: []
      dependencyResults:
        get-service-status.go-service:
          type: get-service-status
          key: get-service-status.go-service
          name: go-service
          description: getting status for service 'go-service' (from module 'go-service')
          output:
            forwardablePorts:
              - name: http
                protocol: TCP
                targetPort: 80
            ingresses:
              - hostname: <redacted>.com
                path: /
                port: 443
                protocol: https
            state: missing
            detail:
              remoteObjects: []
          dependencyResults: {}
    build.node-service:
      type: build
      description: building node-service
      key: build.node-service
      name: node-service
      error:
        command: >-
          /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl
          --context=<redacted> --namespace=garden-system exec -i
          garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build
          -t 127.0.0.1:5000/remote-example/node-service:v-29d3eb4e86 -f
          /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/Dockerfile
          /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/node-service/
        exitCode: 1
        exitCodeName: EPERM
        stdout: "Sending build context to Docker daemon  8.192kB\r\r\nStep 1/8 : FROM node:9-alpine"
        stderr: >-
          Get https://registry-1.docker.io/v2/: x509: certificate signed by
          unknown authority

          command terminated with exit code 1
        all: "Sending build context to Docker daemon  8.192kB\r\r\nStep 1/8 : FROM node:9-alpine\nGet https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\ncommand terminated with exit code 1"
        failed: true
        timedOut: false
        isCanceled: false
        killed: false
    build.go-service:
      type: build
      description: building go-service
      key: build.go-service
      name: go-service
      error:
        command: >-
          /home/<redacted>/.garden/tools/kubectl/baa3b2eba9ab1a15/kubectl
          --context=<redacted> --namespace=garden-system exec -i
          garden-docker-daemon-86b7ffb9df-28mck -c docker-daemon -- docker build
          -t 127.0.0.1:5000/remote-example/go-service:v-0778bf4835 -f
          /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/Dockerfile
          /garden-build/6c15907f-09a3-4d16-bbff-4f884b4ff20b/go-service/
        exitCode: 1
        exitCodeName: EPERM
        stdout: "Sending build context to Docker daemon  5.632kB\r\r\nStep 1/9 : FROM golang:1.8.3-alpine"
        stderr: >-
          Get https://registry-1.docker.io/v2/: x509: certificate signed by
          unknown authority

          command terminated with exit code 1
        all: "Sending build context to Docker daemon  5.632kB\r\r\nStep 1/9 : FROM golang:1.8.3-alpine\nGet https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority\ncommand terminated with exit code 1"
        failed: true
        timedOut: false
        isCanceled: false
        killed: false
    deploy.node-service: null
    deploy.go-service: null
  restartRequired: false
```

**Comment by edvald** [comment]
That one is a little trickier to handle. What's happening there is the docker daemon in the cluster failing to fetch the base image, because it's missing the CA cert. We may be able to work around it but I need to investigate how to handle that, since it's specific to docker (or at least the image we run it from).

**Comment by edvald** [comment]
So I did some digging, and it seems we'd need to add a routine in an init container on the docker daemon Pod, along with the necessary config flag(s). It's not trivial, so we can't quite commit to getting it done within the next week or two. 

Of course, happy to help though, if you have time to contribute the feature yourself :)

**Comment by ajureeruja** [comment]
Thanks for looking into it.  I'll see if I can get some time to familiarize myself with the Garden code base :)

**Comment by ajureeruja** [comment]
Any updates on this? :D

**Comment by edvald** [comment]
We're looking at implementing this in a more generic way through #1478. This would enable you to add certificates to the in-cluster builder container, as well as any other keys, files etc. you may need as part of your build workflow. That should accommodate this specific use-case too, so I think I'll just note the use-case and close this issue. We should work on that soonish, since we have a few other users requesting that.

Feel free to re-open if you don't believe that will cover your case!
