### ISSUE TITLE
Error: "Configured provider <name> has not been registered."

### ISSUE THREAD

**Issue by LeoDupont** [garden-io/garden#1720]
So I created this very simple **garden.yaml** file to setup my GKE cluster with Garden on Windows 10 Pro 1903:

```YAML
kind: Project
name: garden-test
environments:
  - name: dev
providers:
  - name: dev-cluster
    context: gke_project-name_europe-west1-c_dev-cluster
    environments: [dev]
```

With `gke_project-name_europe-west1-c_dev-cluster` my currently selected kubectl context on the same machine.

Then I'm running this command in order to initialize the cluster for Garden:
```bash
garden --env="dev" plugins kubernetes cluster-init
```

And it prints this error:
```
Configured provider 'dev-cluster' has not been registered.

See error.log for detailed error message
```

Here is the content of **error.log**:
```log

[2020-03-20T16:59:22.267Z] Error: Configured provider 'dev-cluster' has not been registered.
    at Object.loadPlugins (C:\snapshot\project\garden-service\tmp\dist\build\src\plugins.js:0)
    at Garden.<anonymous> (C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0)
    at Generator.next (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at new Promise (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at C:\snapshot\project\garden-service\tmp\dist\node_modules\async-lock\lib\index.js:125:12
    at AsyncLock._promiseTry (C:\snapshot\project\garden-service\tmp\dist\node_modules\async-lock\lib\index.js:249:31)
    at exec (C:\snapshot\project\garden-service\tmp\dist\node_modules\async-lock\lib\index.js:124:9)
    at AsyncLock.acquire (C:\snapshot\project\garden-service\tmp\dist\node_modules\async-lock\lib\index.js:140:3)
    at Garden.<anonymous> (C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0)
    at Generator.next (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at new Promise (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at Garden.getPlugins (C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0)
    at Garden.<anonymous> (C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0)
    at Generator.next (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at new Promise (<anonymous>)
    at C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0
    at Garden.getPlugin (C:\snapshot\project\garden-service\tmp\dist\build\src\garden.js:0)
    at PluginsCommand.<anonymous> (C:\snapshot\project\garden-service\tmp\dist\build\src\commands\plugins.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\project\garden-service\tmp\dist\build\src\commands\plugins.js:0)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error Details:
name: dev-cluster
availablePlugins: []
```

I couldn't find any other occurrence of this error on the web :/ 
Any idea?

**Comment by eysi09** [comment]
Hi @LeoDupont, are you on the latest version of Garden (v0.11.9)? There was a similar bug in a previous release that we've since fixed.

You should also be able to get around it by not using the `--env` flag with the command. If the `--env` flag is not set, Garden picks the first environment from the `environments` list or the one set in `defaultEnvironment`.

**Comment by LeoDupont** [comment]
Hi, thanks for your answer.

Yes I am using **Garden version 0.11.9**.

I tried running the command without the `--env` flag (with and without setting `defaultEnvironment: "dev"` in **garden.yaml**) but I got the same error:
```
garden plugins kubernetes cluster-init
```

**Comment by edvald** [comment]
Oops, the config is incorrect, so that doesn't seem to be a bug though. The provider name should be `kubernetes`. Perhaps the error message could be clearer though, e.g. by listing the available providers.

**Comment by LeoDupont** [comment]
@edvald Oh right, it works if I rename my provider `kubernetes`.
I didn't realize the `name` attribute was effectively the type of the provider.

Thank you!
