### ISSUE TITLE
Failed resolving provider local-kubernetes

### ISSUE THREAD

**Issue by toby-1-kenobi** [garden-io/garden#1856]
### Current Behavior

`$ ~/.garden/bin/garden validate --log-level debug`

```
Retrieved client auth token from local config db
ℹ providers                 → Getting status...
   Execing '/home/toby/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=minikube --context=minikube config view --raw' in /home/toby/.garden/tools/kubectl/804c71b3e6ad5976
   An attempt to get kind version failed with Error: Command "kind version" failed with code undefined:
   Using minikube's ingress addon
   Execing '/home/toby/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=minikube --context=minikube config view --raw' in /home/toby/.garden/tools/kubectl/804c71b3e6ad5976

Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
clusters[10].cluster.server is missing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- local-kubernetes

See error.log for detailed error message
 providers                 → Getting status...
```
`$ cat error.log`
```
[2020-06-04T01:54:43.739Z] Error: clusters[10].cluster.server is missing
    at /snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config_types.js:30:19
    at Function.<anonymous> (/snapshot/project/garden-service/tmp/dist/node_modules/underscore/underscore.js:205:24)
    at Object.newClusters (/snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config_types.js:6:14)
    at KubeConfig.loadFromString (/snapshot/project/garden-service/tmp/dist/node_modules/@kubernetes/client-node/dist/config.js:105:40)
    at /snapshot/project/garden-service/tmp/dist/build/src/plugins/kubernetes/api.js:0
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/src/plugins/kubernetes/api.js:0)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

[2020-06-04T01:54:43.742Z] Error: Failed resolving one or more providers:
- local-kubernetes
    at Garden.<anonymous> (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/garden-service/tmp/dist/build/src/garden.js:0)
Error Details:
rawConfigs: []
taskResults:
  resolve-provider.exec:
    type: resolve-provider
    key: resolve-provider.exec
    name: exec
    description: resolving provider exec
    completedAt: '2020-06-04T01:54:42.825Z'
    batchId: ebc41a65-401c-49d7-9c78-8df4c46fc778
    output:
      name: exec
      dependencies: []
      moduleConfigs: []
      config:
        name: exec
        path: /home/toby/projects/garden/examples/demo-project
      status:
        ready: true
        outputs: {}
    dependencyResults: {}
  resolve-provider.container:
    type: resolve-provider
    key: resolve-provider.container
    name: container
    description: resolving provider container
    completedAt: '2020-06-04T01:54:42.825Z'
    batchId: 5697b44e-42a0-42e3-ae98-2f21691994f3
    output:
      name: container
      dependencies: []
      moduleConfigs: []
      config:
        name: container
        path: /home/toby/projects/garden/examples/demo-project
      status:
        ready: true
        outputs: {}
    dependencyResults: {}
  resolve-provider.local-kubernetes:
    type: resolve-provider
    description: resolving provider local-kubernetes
    key: resolve-provider.local-kubernetes
    name: local-kubernetes
    error: {}
    completedAt: '2020-06-04T01:54:43.736Z'
    batchId: 5697b44e-42a0-42e3-ae98-2f21691994f3
messages: []
```

### Expected behavior

something without error messages

### Reproducible example

I installed Garden with this command:
`$ curl -sL https://get.garden.io/install.sh | bash`

I'm using minikube with kvm2
`$ kubectl config current-context`
```
minikube
```
`$ kubectl get nodes`
```
NAME       STATUS   ROLES    AGE   VERSION
minikube   Ready    master   35m   v1.18.3
```
The error comes whenever I use any garden command

### Additional context

I'm trying this with the quick start demo project
`$ git clone https://github.com/garden-io/garden.git`
`$ cd garden/examples/demo-project`

I tried explicitly giving the local kubernetes context as minkube:
`$ cat garden.yml`
```
kind: Project
name: demo-project
# defaultEnvironment: "remote" # Uncomment if you'd like the remote environment to be the default for this project.
environments:
  - name: local
  - name: remote
providers:
  - name: local-kubernetes
    environments: [local]
    context: minikube
  - name: kubernetes
    environments: [remote]
    # Replace these values as appropriate
    context: gke_garden-dev-200012_europe-west1-b_garden-dev-1
    namespace: demo-project-testing-${local.env.USER || local.username}
    defaultHostname: ${local.env.USER || local.username}-demo-project.dev-1.sys.garden
    buildMode: cluster-docker
```
### Your environment

Ubuntu 20.04

`garden version`
```
0.11.14
```

`kubectl version`
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

`docker version`
```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       aa6a989
  Built:            Fri May  8 19:41:43 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by toby-1-kenobi** [comment]
I installed kind, but it didn't help:
`$ garden validate --log-level debug`
````
Retrieved client auth token from local config db
ℹ providers                 → Getting status...
   Execing '/home/toby/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=minikube --context=minikube config view --raw' in /home/toby/.garden/tools/kubectl/804c71b3e6ad5976
   Found kind with the following version details kind v0.8.1 go1.14.2 linux/amd64
   Execing '/home/toby/.garden/tools/kubectl/804c71b3e6ad5976/kubectl --context=minikube --context=minikube config view --raw' in /home/toby/.garden/tools/kubectl/804c71b3e6ad5976

Failed resolving provider local-kubernetes. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
clusters[10].cluster.server is missing
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed resolving one or more providers:
- local-kubernetes

See error.log for detailed error message
 providers                 → Getting status...
```

**Comment by mwebler** [comment]
Hey there! @toby-1-kenobi  did you find how to solve it? I am having the same issues trying to follow the getting started tutorial or using the demo-project example. I get the error for either local `docker-desktop` or remote GKE contexts:
```

Failed resolving provider local-kubernetes. Here is the output:
clusters[15].cluster.server is missing
```

The full logs with `--log-level 5` are attached: [error.log](https://github.com/garden-io/garden/files/5874798/error.log)

I'm on MacOS Big Sur 11.1 and using Garden v0.12.15.

Stale bot suggests tagging a maintainer, so maybe @edvald and @eysi09 can help out to see if we should reopen this?

**Comment by mwebler** [comment]
So, it seems that something was going wrong with one of the many contexts I had set on my kubeconfig. Maybe Garden is trying to parse some invalid config from an unused context?

After running `kubectl config unset contexts` to clear the existing contexts and connecting again to my remote GKE cluster everything worked fine.
