### ISSUE TITLE
Error: write EPIPE when killing long running processes

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#2370]
### Current Behavior

When killing the `garden dev` command (or other watch commands), this error is sometimes thrown:

```
Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:677:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at Object.close (internal/cluster/child.js:152:5)
    at Server.close (net.js:1610:18)
    at stopPortProxy (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/proxy.js:0)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/proxy.js:0
    at runHook (/snapshot/project/tmp/pkg/cli/node_modules/async-exit-hook/index.js:56:10)
    at Array.map (<anonymous>)
    at exit (/snapshot/project/tmp/pkg/cli/node_modules/async-exit-hook/index.js:71:8)
    at process.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/async-exit-hook/index.js:116:3)
    at process.emit (events.js:315:20)
    at process.emit (/snapshot/project/tmp/pkg/cli/node_modules/source-map-support/source-map-support.js:495:21)
 ```

Looks like Node.js is trying to write to a stream that's already been closed. See [this Node.js issue](https://github.com/nodejs/node/issues/947) for more.  

### Expected behavior

There shouldn't be an uncaught error.

### Reproducible example

It's a little tricky to reproduce. Perhaps it could be done at the code level?

### Workaround

There's no real workaround but the issue is harmless, it's just annoyin.

### Suggested solution(s)

The suggestions from the Node.js issue linked to above.

### Additional context

N/A

### Your environment

Garden v0.12.21

**Comment by eysi09** [comment]
I put `pirority:low` for now since this kind of harmless and we have more important things in the pipeline. We should reconsider though if users are seeing this all the time.

**Comment by edvald** [comment]
Just posted a fix, we were just trying to close an already-closed server.
