### ISSUE TITLE
getting started project: integration tests fail

### ISSUE THREAD

**Issue by MFAshby** [garden-io/garden#2735]
### Current Behavior
Follow the getting started documentation. 
Get to the test step and run tests: https://docs.garden.io/getting-started/4-deploy-and-test
Tests fail with the following logging
```
✖ frontend                  → Running integ tests → Failed! (took 132.1 sec)

Failed running integ tests in module frontend. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> frontend@1.0.0 integ /app
> node_modules/mocha/bin/mocha test/integ.js



  GET /call-backend
    1) should respond with a message from the backend service


  0 passing (2s)
  1 failing

  1) GET /call-backend
       should respond with a message from the backend service:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/app/test/integ.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

### Expected behavior

Tests pass

### Reproducible example

Example already present

### Workaround

The problem appears to be that the ingress class changed in microk8s version 1.20: https://github.com/ubuntu/microk8s/issues/2035

The ingress resources created by garden are ignored, this can be seen in the ingress controller logs: 
```
I0117 20:21:12.617931       6 store.go:420] "Ignoring ingress because of error while validating ingress class" ingress="hello-garden-default/backend-0" error="ingress class annotation is not equal to the expected by Ingress Controller"
I0117 20:21:12.617993       6 store.go:420] "Ignoring ingress because of error while validating ingress class" ingress="hello-garden-default/frontend-0" error="ingress class annotation is not equal to the expected by Ingress Controller"
I0117 20:21:12.618032       6 store.go:420] "Ignoring ingress because of error while validating ingress class" ingress="hello-garden-default/frontend-1" error="ingress class annotation is not equal to the expected by Ingress Controller"
```

This can be worked around by adding the new ingressClassName element to the ingress.spec: 
```
kubectl edit ingress/backend-0 -n hello-garden-default
```
```
...
 25 spec:
 26   ingressClassName: public # Need to explicitly add this
 27   rules:
...
```

There doesn't appear to be any way to set this on a container resource: https://docs.garden.io/reference/module-types/container

### Suggested solution(s)

Choose an appropriate ingressClassName when ingress resources are created. Although this should have been picked up by the [default ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#default-ingress-class) mechanism, it appears that didn't work.

### Your environment

* Linux, manjaro 

* microk8s: 
```
$ snap list microk8s
Name      Version  Rev   Tracking     Publisher   Notes
microk8s  v1.21.8  2819  1.21/stable  canonical✓  classic
```

```
$ garden version
0.12.34
```

**Comment by MFAshby** [comment]
I think [this code](https://github.com/garden-io/garden/blob/2fb8a119b48796e18e3247ddbe34c69c64223c14/core/src/plugins/kubernetes/container/ingress.ts#L66) to create the ingress is preferring to use the old API and add the deprecated ingress-class annotation instead of setting ingressClassName. I still don't fully understand why the `public` ingress class (which is marked as default) didn't pick up the ingress resources.

I would suggest: 
- prefer the newer API by default if it's available.
- detect and set an appropriate ingressClassName , possible selection criteria: select from the user's config > or choose the default one > or choose the only available one > or install one if there isn't one installed > or panic if there's more than 1 and neither is default (and prompt the user to select one in their configuration)

**Comment by edvald** [comment]
Thanks for digging into this @MFAshby! This is super helpful. cc @thsig (who worked on this last)

At a glance it seems this is specific to microk8s, but we do want that to work out of the box (and already have specific provisions for it in the `local-kubernetes` provider).

This ingress API migration has been quite painful overall, not just for us mind you, but we should give it our best.

@MFAshby does it work if you set `ingressClass: public` on the `local-kubernetes` provider config?

**Comment by MFAshby** [comment]
@edvald thanks for the speedy response, that seems to have done _something_, and now all the ingress resources have assigned IP addresses

Setting applied like so:
```
providers:
  - name: local-kubernetes
    ingressClass: public
```

Ingresses got a step further (ADDRESS column was previously empty)
```
$ kubectl get ingresses --all-namespaces
NAMESPACE              NAME         CLASS    HOSTS                           ADDRESS     PORTS   AGE
hello-garden-default   frontend-1   <none>   hello-garden.local.app.garden   127.0.0.1   80      11m
hello-garden-default   frontend-0   <none>   hello-garden.local.app.garden   127.0.0.1   80      11m
hello-garden-default   backend-0    <none>   hello-garden.local.app.garden   127.0.0.1   80      11m
```

**Comment by MFAshby** [comment]
It's possible the ingress controller was _trying_ to use the annotation instead of the new field, and then because the class name was `nginx` and not `public` it didn't match and so wouldn't handle that ingress resource. Looks like there was some confusion about precedence here: https://github.com/kubernetes/ingress-nginx/issues/8103

I'm going to try on a later microk8s version since 1.23 is out.

**Comment by MFAshby** [comment]
microk8s version 1.23 a similar problem, except it's setting the ingressClassName field now instead of the annotation (I think the older ingress API was removed in this version) 

Segment from ingress/frontend-0:
```
spec:
  ingressClassName: nginx
  rules:
```

If I add the provider configuration `ingressClass: public` as you suggested, it works correctly.

**Comment by edvald** [comment]
Interesting! I'm not quite familiar enough with microk8s day-to-day, but I wonder if setting that as a default specifically for microk8s would make sense? And importantly, not break existing deployments.

**Comment by MFAshby** [comment]
>  I wonder if setting that as a default specifically for microk8s would make sense? 

It would probably work, although I expect inspecting the cluster to see what ingress classes are available would be a more robust solution and less provider specific. Note that upgrading microk8s itself doesn't cause addons like the ingress controller to get upgraded as well: https://microk8s.io/docs/upgrading. This means it's possible to be running latest microk8s with an older ingress controller that still uses class name 'nginx'.
