### ISSUE TITLE
Unhandled promise rejection when updating a git repo that has been linked / dev mode

### ISSUE THREAD

**Issue by ohookins** [garden-io/garden#2845]
### Current Behavior

I have a module linked to another directory locally that is also a git repository. When updating that git repo (during which time some changes are made to the directory structure, I get the following error.

```
(node:64585) UnhandledPromiseRejectionWarning: Error: Path /Users/ohookins/src/github.com/xxxx/.git/objects/pack is not in a git repository root. Garden must be run from within a git repo. Please run `git init` if you're starting a new project and repository, or move the project to an existing repository, and try again.
    at wrapped.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/vcs/git.js:0)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/vcs/git.js:0)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm running this from within `garden dev` and file syncing is set up for this location.

### Expected behavior

No error.

### Reproducible example

- Set up a remote module, link it to another local directory that is also a git repository.
- Set up dev mode syncing for the source directory of the build
- Run `garden dev`
- Run a `git pull` or some other operation that alters the directory structure of the linked source directory.

### Your environment

* **OS:** MacOS 11.6.4
* **How I'm running Kubernetes:** EKS 1.20

`garden version`
0.12.35

**Comment by vvagaytsev** [comment]
@ohookins could you please check if this is still reproducible with Garden `0.12.42`? We've just released it.

**Comment by ohookins** [comment]
@vvagaytsev I *think* it was just changing branches on a linked repo or something, although in the case of any branches I've tried today I couldn't get it to fail. If I check out the initial commit of the linked repo (where there's basically nothing there) I do get this error:

```
(node:83008) UnhandledPromiseRejectionWarning: xxxx: Error: Module xxxx neither specifies image nor provides Dockerfile
    at Object.getDeploymentImageId (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/container/helpers.ts:160:13)
    at AsyncFunction.getContainerModuleOutputs (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/container/container.ts:238:46)
    at handler (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins.ts:603:16)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1281:16
    at AsyncFunction.k8sGetContainerModuleOutputs (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/container/handlers.ts:59:29)
    at Object.handler (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins.ts:603:16)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1234:38
    at ActionRouter.getModuleOutputs (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:350:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Object.moduleFromConfig (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/types/module.ts:111:23)
    at ModuleResolver.resolveModule (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/resolve-module.ts:546:20)
    at processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/resolve-module.ts:163:40)
(Use `garden --trace-warnings ...` to show where the warning was created)
(node:83008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:83008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

But that's a different error. :shrug:

**Comment by ohookins** [comment]
If you can't get this reproduced by anyone else, I'm happy for you to close it! I haven't seen it since, but we've only just gotten our stuff together in order to be able to run dev mode anyway.

**Comment by vvagaytsev** [comment]
Ok, thank you @ohookins! An error like `Error: Module xxxx neither specifies image nor provides Dockerfile` means there is no `Dockerfile` in the module directory, so the module can't be built. You wrote that you tried it with an empty linked repo, so that's an excepted error.

I can not reproduce this issue too. So I'm closing this, feel free to reopen it if the issue happens again. Thank you for your help!
