### ISSUE TITLE
events.js - Unhandled 'error' event when running hello-world on Windows

### ISSUE THREAD

**Issue by ellenkorbes** [garden-io/garden#297]
```
Good morning! Let's get your environment wired up...

\ hello-function            → Running unit tests
\ hello-function            → Checking status
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
PS C:\Users\t480\code\garden\examples\hello-world>
```

**Comment by edvald** [comment]
It's not finding npm, hmm. The hello-world example currently depends on npm, which may not be a good idea, but how could it be that you have garden installed but not npm...?

**Comment by edvald** [comment]
Does npm work on the command line?

**Comment by ellenkorbes** [comment]
Yes and NPM is installed, 100% sure.
