### ISSUE TITLE
Deploy to remote k8s fails with “Unable to query registry for image status: Unexpected server response: 403"

### ISSUE THREAD

**Issue by MaximumQuiet** [garden-io/garden#3207]
### Current Behavior
Hi! I'm currently setup a k8s cluster (Talos) with Garden, and stuck on enabling in-cluster building with Kaniko. After garden --env... deploy, I receive the following error:

```
Error: Unable to query registry for image status: Unexpected server response: 403
    at skopeoBuildStatus (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/container/build/common.ts:264:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1303:24
    at ActionRouter.getBuildStatus (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:359:20)
    at wrapped.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/build.ts:132:22)
    at TaskNode.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:801:20)
    at wrapped.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:436:18)
```

### Expected behavior
Garden deploy without errors.

### Additional context
I tried setting both local (127.0.0.1:5000) and remote (DockerHub) deploymentRegistry, but the error is permanent.

docker-registry itself is up and running:
`garden-system            garden-docker-registry-645768d844-47j94       1/1     Running   0                3d17h   10.244.3.12   talos-3zf-652   <none>           <none>`

### Your environment
* **OS:** macOS Ventura 13.0
* **How I'm running Kubernetes:** Talos OS

`garden version`
0.12.44

**Comment by vvagaytsev** [comment]
Thanks for reporting this @MaximumQuiet ! We'll take a look soon.

**Comment by vvagaytsev** [comment]
In-cluster registries are no longer supported in 0.13. Closing this as stale.
