### ISSUE TITLE
Cannot connect to http k8s endpoints, error implies https required.

### ISSUE THREAD

**Issue by kylev** [garden-io/garden#3411]
### Current Behavior

At my company, we use [SDM](https://www.strongdm.com/) to expose remote clusters on our local workstations via plain HTTP. The server URL is `http://127.0.0.1:18447`, and the encryption is done by the SDM client tunnel. New versions of garden after 0.12.46 have started throwing errors when running `halo dev`:

```
[2022-12-02T17:03:10.709Z] Error: Unable to connect to Kubernetes cluster. Got error:

TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at prepareNamespaces (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/namespace.ts:242:11)
    at Object.getEnvironmentStatus (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/init.ts:85:22)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1271:24
    at wrapped.ensurePrepared (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/resolve-provider.ts:339:18)
    at wrapped.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/resolve-provider.ts:241:20)
    at TaskNode.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:801:20)
    at wrapped.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:436:18)
```

### Expected behavior

We should be able to connect and operate on contexts/servers that use both http and https.

### Reproducible example

Any context with http:// in the `server` URL.

### Workaround

Runstall older 0.12.46 version.

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS over SDM

`garden version`
`0.12.47`

**Comment by Orzelius** [comment]
Hey @kylev, thanks for pointing his out. We will be working on his immediately and hopefully will have a fix out in a couple of days.

**Comment by kylev** [comment]
I suspect this was caused by the client update moving to HEAD? I'm still learning the codebase.

**Comment by Orzelius** [comment]
Yes that's most likely it. This is the pr https://github.com/garden-io/garden/pull/3374
I really wanted to get this done this week but failed to do so.

Could you try setting the `HTTP_PROXY` env and see if that helps. If it does the issue stems from this commit https://github.com/garden-io/garden/pull/3374/commits/656aee560e5d3807ef8df0a7f71dc5cfe4794884 otherwise it's the k8s client update in general.

Sorry for this taking longer than expected.

**Comment by kylev** [comment]
Yup, looks like it starts working if I set env `NO_PROXY=blah` before running.
