### ISSUE TITLE
Sudden termination during a build when using Kaniko on GKE Autopilot

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#3469]
## Bug

Kaniko pods appear to run without issue until sudden termination. No errors are reported or logs provided on termination other than a misleading error:
```
Failed building flask-app-image. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed to start Pod kaniko-flask-app-image-12890a.
```

I can confirm the build pod runs and will run until sudden termination, every time.

### Current Behavior

Logs from Kaniko build pod in-cluster:
```
Collecting typing-extensions==4.4.0
  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting urllib3==1.26.12
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 138.7 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.11/site-packages (from gunicorn==20.1.0->-r requirements.txt (line 31)) (65.5.0)
Building wheels for collected packages: greenlet, markupsafe, psycopg2, sqlalchemy
  Building wheel for greenlet (setup.py): started
```

Output from `garden deploy`:
```
✖ flask-app-image           → Building image flask-app:v-093dbb2ae3...
-> Deploying garden-util service in flask-cockroachdb-example-worldofgeese namespace (was outdated) → Done!
ℹ garden-util               → Resources ready
-> Deploying garden-util service in flask-cockroachdb-example-worldofgeese namespace (was outdated) → Done!
ℹ garden-util               → Resources ready
✔ my-cockroachdb            → Deploying version v-12340e954b... → Already deployed
Garden's error:
Failed building flask-app-image. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Failed to start Pod kaniko-flask-app-image-12890a.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1 deploy action(s) failed!
```

### Expected behavior

Kaniko pod should build and run to finish.

### Reproducible example

Use the `[gardenify](https://github.com/worldofgeese/flask-cockroachdb-devcontainer/tree/gardenify)` branch of my Dev Container with this gist substituted for the `kubernetes` provider block.

### Workaround

Use local build mode (`cluster-buildkit` is also unable to be used, see $PLACEHOLDER).

### Your environment

* **OS:** Windows 11 with WSL
* **How I'm running Kubernetes:** GKE Autopilot

`garden version`
0.12.48

**Comment by stefreak** [comment]
@worldofgeese hi, did you look into the logs of why it failed to start?

**Comment by worldofgeese** [comment]
@stefreak can you clarify? I've put all the logs here in the issue. The mysterious part is build pods terminate as they're building with no other error logs from Garden or the build pod itself.

**Comment by worldofgeese** [comment]
I a new deploy this morning and finally received an error from `garden deploy` without any changes on my side:

```
vscode@89dbebc771dc:/workspaces/flask-cockroachdb-devcontainer$ garden deploy
Deploy 

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🌍  Running in namespace flask-cockroachdb-example-worldofgeese in environment dev
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✔ providers                 → Getting status... → Done
✔ graph                     → Resolving 4 modules... → Done
✔ seed-db                   → Checking result... → Done
✔ create-db                 → Checking result... → Done
✔ my-cockroachdb            → Building version v-3a6f49ac91... → Done (took 1.1 sec)
✖ flask-app-image           → Building image flask-app:v-be895403fc...
-> Deploying garden-util service in flask-cockroachdb-example-worldofgeese namespace (was outdated) → Done!
ℹ garden-util               → Resources ready
-> Deploying garden-util service in flask-cockroachdb-example-worldofgeese namespace (was outdated) → Done!
ℹ garden-util               → Resources ready
✔ my-cockroachdb            → Deploying version v-c40cf8b4a2... → Done (took 189 sec)
   ℹ my-cockroachdb            → Resources ready

Failed building flask-app-image. Here is the output:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Pod container was OOMKilled.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 deploy action(s) failed!
```

The error log shows the cause:

```
[2023-01-04T13:11:32.954Z] Error: Pod container was OOMKilled.
    at PodRunner.awaitRunningPod (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/run.ts:874:15)
    at PodRunner.runAndWait (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/run.ts:823:24)
    at runKaniko (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/container/build/kaniko.ts:445:18)
    at kanikoBuild (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/plugins/kubernetes/container/build/kaniko.ts:161:20)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:1303:24
    at ActionRouter.build (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/actions.ts:415:16)
    at wrapped.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/build.ts:149:16)
    at TaskNode.process (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:801:20)
    at wrapped.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/task-graph.ts:436:18)

Error Details:

logs: ''
exitCode: 137
containerStatus:
  image: 'gcr.io/kaniko-project/executor:v1.8.1-debug'
  imageID: ''
  lastState:
    terminated:
      exitCode: 137
      finishedAt: null
      message: >-
        The container could not be located when the pod was deleted.  The
        container used to be Running
      reason: ContainerStatusUnknown
      startedAt: null
  name: kaniko
  ready: false
  restartCount: 1
  started: false
  state:
    terminated:
      exitCode: 137
      finishedAt: null
      message: The container could not be located when the pod was terminated
      reason: ContainerStatusUnknown
      startedAt: null
podStatus:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2023-01-04T13:08:07.000Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2023-01-04T13:11:25.000Z'
      reason: PodFailed
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2023-01-04T13:11:25.000Z'
      reason: PodFailed
      status: 'False'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2023-01-04T13:07:50.000Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - ~containerStatus
  hostIP: 10.0.0.20
  initContainerStatuses:
    - containerID: >-
        containerd://3b3de4be0a3981df0807b3f4653a356031bfc6cc5773c83ea350cbefd40d13bd
      image: 'docker.io/gardendev/k8s-util:0.5.6'
      imageID: >-
        docker.io/gardendev/k8s-util@sha256:dce403dc7951e3f714fbb0157aaa08d010601049ea939517957e46ac332073ad
      lastState: {}
      name: init
      ready: true
      restartCount: 0
      state:
        terminated:
          containerID: >-
            containerd://3b3de4be0a3981df0807b3f4653a356031bfc6cc5773c83ea350cbefd40d13bd
          exitCode: 0
          finishedAt: '2023-01-04T13:08:04.000Z'
          reason: Completed
          startedAt: '2023-01-04T13:07:54.000Z'
  message: >-
    Pod ephemeral local storage usage exceeds the total limit of containers
    1Gi. 
  phase: Failed
  podIP: 192.168.0.230
  podIPs:
    - ip: 192.168.0.230
  qosClass: Guaranteed
  reason: Evicted
  startTime: '2023-01-04T13:07:50.000Z'


[2023-01-04T13:11:32.992Z] Error: 1 deploy action(s) failed!
    at handleProcessResults (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/commands/base.ts:532:19)
    at DeployCommand.action (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/commands/deploy.ts:270:32)
    at GardenCli.runCommand (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:513:20)
    at GardenCli.run (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/cli/cli.ts:672:26)
    at Object.runCli (/snapshot/project/tmp/pkg/cli/src/cli.ts:41:14)

Error Details:

results:
  build.flask-app-image:
    type: build
    description: building flask-app-image
    key: build.flask-app-image
    name: flask-app-image
    error:
      detail:
        logs: ''
        exitCode: 137
        containerStatus:
          image: 'gcr.io/kaniko-project/executor:v1.8.1-debug'
          imageID: ''
          lastState:
            terminated:
              exitCode: 137
              finishedAt: null
              message: >-
                The container could not be located when the pod was deleted. 
                The container used to be Running
              reason: ContainerStatusUnknown
              startedAt: null
          name: kaniko
          ready: false
          restartCount: 1
          started: false
          state:
            terminated:
              exitCode: 137
              finishedAt: null
              message: The container could not be located when the pod was terminated
              reason: ContainerStatusUnknown
              startedAt: null
        podStatus:
          conditions:
            - lastProbeTime: null
              lastTransitionTime: '2023-01-04T13:08:07.000Z'
              status: 'True'
              type: Initialized
            - lastProbeTime: null
              lastTransitionTime: '2023-01-04T13:11:25.000Z'
              reason: PodFailed
              status: 'False'
              type: Ready
            - lastProbeTime: null
              lastTransitionTime: '2023-01-04T13:11:25.000Z'
              reason: PodFailed
              status: 'False'
              type: ContainersReady
            - lastProbeTime: null
              lastTransitionTime: '2023-01-04T13:07:50.000Z'
              status: 'True'
              type: PodScheduled
          containerStatuses:
            - ~results~build.flask-app-image~error~detail~containerStatus
          hostIP: 10.0.0.20
          initContainerStatuses:
            - containerID: >-
                containerd://3b3de4be0a3981df0807b3f4653a356031bfc6cc5773c83ea350cbefd40d13bd
              image: 'docker.io/gardendev/k8s-util:0.5.6'
              imageID: >-
                docker.io/gardendev/k8s-util@sha256:dce403dc7951e3f714fbb0157aaa08d010601049ea939517957e46ac332073ad
              lastState: {}
              name: init
              ready: true
              restartCount: 0
              state:
                terminated:
                  containerID: >-
                    containerd://3b3de4be0a3981df0807b3f4653a356031bfc6cc5773c83ea350cbefd40d13bd
                  exitCode: 0
                  finishedAt: '2023-01-04T13:08:04.000Z'
                  reason: Completed
                  startedAt: '2023-01-04T13:07:54.000Z'
          message: >-
            Pod ephemeral local storage usage exceeds the total limit of
            containers 1Gi. 
          phase: Failed
          podIP: 192.168.0.230
          podIPs:
            - ip: 192.168.0.230
          qosClass: Guaranteed
          reason: Evicted
          startTime: '2023-01-04T13:07:50.000Z'
      type: out-of-memory
    startedAt: '2023-01-04T13:03:23.441Z'
    completedAt: '2023-01-04T13:11:32.858Z'
    batchId: 75c21cae-9d9f-4d93-b2ba-d40ea80999b5
    version: v-be895403fc
```

This got me looking into Autopilot's default resource requests:

> Autopilot assigns a default [ephemeral storage request of 1 GiB](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#defaults) if a resource request is not specified. The ephemeral storage limit must be within [10 MiB and 10 GiB](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#min-max-requests) for all compute classes and hardware configurations.

As far as I can see there is no way to specify a resource request for `kaniko` using Garden, is that correct?

**Comment by twelvemo** [comment]
@tedchang77 this is already implemented see https://docs.garden.io/reference/providers/kubernetes#providers-.resources.builder
Can you try to set these to sensible values and report if it solves your problem?

**Comment by vvagaytsev** [comment]
@garden-io/sre would you be interested in updating the docs for this?
