### ISSUE TITLE
Fix tests in `plugins/container/helpers.ts`

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#3569]
**Problem 1.**

Two tests (`should use image name including version if specified` and `should use image name if specified with commit hash if no version is set`) fail with error:
```
Module module-a neither specifies image nor provides Dockerfile
```

This happens because of call to [`router: await garden.getActionRouter()`](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L98) in the [`getTestBuildAction` helper](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L91).

The statement `await garden.getActionRouter()` scans the Garden configs from the disk, and does use the [custom image name defined in the test](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L184).

There should be a way to init the action router with the customized config. This looks like a bug in the test setup.

**Problem 2.**

~There seem to be 2 different places to specify an image name for the Build step:~
1. ~[`targetImage` in `ContainerModuleBuildSpec`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/moduleConfig.ts#L66)~
2. ~[`image` in `ContainerModuleSpec`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/moduleConfig.ts#L75)~

~What's the difference between those 2? Which one should be used in [`container.ts`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/container.ts#L149)?~

The [`targetImage` field name in `ContainerModuleBuildSpec`](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/moduleConfig.ts#L66) doesn't match the corresponding [`target` field name](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/moduleConfig.ts#L89) in the [`containerBuildSpecSchema ` schema definition](https://github.com/garden-io/garden/blob/0.13/core/src/plugins/container/moduleConfig.ts#L87).

**Problem 3.**

This happens in `should use local id if no image name is set` spec:
```
TypeError: Cannot read property 'basePath' of undefined
    at resolveTemplates (src/graph/actions.ts:341:29)
    at preprocessActionConfig (src/graph/actions.ts:366:3)
    at actionFromConfig (src/graph/actions.ts:115:18)
    at getTestBuildAction (test/unit/src/plugins/container/helpers.ts:93:28)
    at getResolvedTestBuildAction (test/unit/src/plugins/container/helpers.ts:104:20)
    at Context.<anonymous> (test/unit/src/plugins/container/helpers.ts:226:22)
```

The value of [`config.internal`](https://github.com/garden-io/garden/blob/0.13/core/src/graph/actions.ts#L341) is `undefined` because a [wrong config object](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L96) is provided instead of a valid `ActionConfig` in the [`getTestBuildAction ` helper](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L91). The object [`parsed.moduleConfig.buildConfig`](https://github.com/garden-io/garden/blob/0.13/core/test/unit/src/plugins/container/helpers.ts#L96) has type [`any`](https://github.com/garden-io/garden/blob/0.13/core/src/config/module.ts#L261), but the [function `actionFromConfig`](https://github.com/garden-io/garden/blob/5fff75414dab9b26017c21fe697a7a5c473f0044/core/src/graph/actions.ts#L97) expects an `ActionConfig` instead.

**Comment by vvagaytsev** [comment]
Thanks for your interest @tharun208! This issue is quite hard to fix. We can recommend starting with something labeled as [good first issue](https://github.com/garden-io/garden/labels/good%20first%20issue) or some minor bug fixes which are not labeled as [0.13](https://github.com/garden-io/garden/labels/0.13).
