### ISSUE TITLE
Garden logs -t doesn't handle service restarts

### ISSUE THREAD

**Issue by drubin** [garden-io/garden#411]
### Current Behavior

When running `garden logs -t` and `garden dev` and you make a change to a service garden doesn't detect this and stops being able to follow the logs

There is also a Deprecation warning from moment?

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: rpc, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/app/garden-service/node_modules/moment/moment.js:320:98)
    at configFromString (/app/garden-service/node_modules/moment/moment.js:2368:15)
    at configFromInput (/app/garden-service/node_modules/moment/moment.js:2594:13)
    at prepareConfig (/app/garden-service/node_modules/moment/moment.js:2577:13)
    at createFromConfig (/app/garden-service/node_modules/moment/moment.js:2544:44)
    at createLocalOrUTC (/app/garden-service/node_modules/moment/moment.js:2631:16)
    at createLocal (/app/garden-service/node_modules/moment/moment.js:2635:16)
    at hooks (/app/garden-service/node_modules/moment/moment.js:12:29)
    at Stream.proc.stdout.pipe.on (/app/garden-service/build/plugins/kubernetes/actions.js:295:29)
    at Stream.emit (events.js:182:13)
    at drain (/app/garden-service/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/app/garden-service/node_modules/through/index.js:45:5)
    at emit (/app/garden-service/node_modules/split/index.js:37:14)
    at Stream.<anonymous> (/app/garden-service/node_modules/split/index.js:60:7)
    at _end (/app/garden-service/node_modules/through/index.js:65:9)
    at Stream.stream.end (/app/garden-service/node_modules/through/index.js:74:5)
    at Socket.onend (_stream_readable.js:628:10)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
result                    →                          → error: code = Unknown desc = Error: No such container: fb49980718a85976f30d95d21cc38b66efe344825a8cef48708a311a468967bc
vote                      →                          → error: code = Unknown desc = Error: No such container: c35073d998796767d1b351a1a0e965491e2a1e80239b3834ae0ae00319d8b6ea
db                        →                          → error: code = Unknown desc = Error: No such container: f561dc0e83bb93b8d281727e4ca40909f2c0295982b0095e63788098c769fb91
```

 ### Expected behavior

To be able to get the logs as things change (thats the point fo being able to view the logs with -t)

 ### Reproducible example

1. `garden deploy`
1. `garden logs -t` (keep runinng)
1. Edit a file to trigger a rebuild `echo " " > services/vote/templates/index.html`
1. `garden deploy`

 ### Suggested solution(s)

na.

 ### Additional context

Na 
 ### Your environment

Garden version: 0.8.0

**Comment by edvald** [comment]
I think I see the issue, looking into it.

**Comment by edvald** [comment]
Hmm actually I'm having trouble reproducing this. We're basically just using `kubectl logs --follow` behind the scenes, which is supposed to be able to deal with redeploys. Can you give me more specifics on the stack you're working with?

**Comment by drubin** [comment]
`kubectl logs $PODNAME` kubernetes api doesn't follow new pods that are created which is what happens when you redeploy a service :)

Any of the example projects will show this just follow the steps.

**Comment by edvald** [comment]
I can see that now, I incorrectly assumed `kubectl logs --follow` actually listened for new pods, but I still cannot reproduce the error message you got there. (And of course I followed the steps 🙄).

**Comment by drubin** [comment]
Oo seems like there is an issue with the task graph which we are fixing (the logs say its redeployed but it doesn't actually redeploy on file change.

New steps inside multi-container

1. `garden deploy` 
1. `garden logs -t` (keep runinng) 
1. Edit file `echo " " > services/vote/templates/index.html`
1. `garden deploy`

**Comment by baspetersdotjpeg** [comment]
This behavior appears to persist (or was somehow re-introduced?) in 0.10.15. When running `garden logs <service> -f` and the service is redeployed, it will throw a stacktrace and then exit:

```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: rpc, _f: undefined, _strict: undefined, _locale: [object Object]
Error:
    at Function.createFromInputFallback (/snapshot/dist/node_modules/moment/moment.js:320:98)
    at configFromString (/snapshot/dist/node_modules/moment/moment.js:2385:15)
    at configFromInput (/snapshot/dist/node_modules/moment/moment.js:2611:13)
    at prepareConfig (/snapshot/dist/node_modules/moment/moment.js:2594:13)
    at createFromConfig (/snapshot/dist/node_modules/moment/moment.js:2561:44)
    at createLocalOrUTC (/snapshot/dist/node_modules/moment/moment.js:2648:16)
    at createLocal (/snapshot/dist/node_modules/moment/moment.js:2652:16)
    at hooks (/snapshot/dist/node_modules/moment/moment.js:12:29)
    at Stream.proc.stdout.pipe.on (/snapshot/dist/build/src/plugins/kubernetes/logs.js:0)
    at Stream.emit (events.js:189:13)
    at drain (/snapshot/dist/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/snapshot/dist/node_modules/through/index.js:45:5)
    at emit (/snapshot/dist/node_modules/split/index.js:37:14)
    at Stream.<anonymous> (/snapshot/dist/node_modules/split/index.js:60:7)
    at _end (/snapshot/dist/node_modules/through/index.js:65:9)
    at Stream.stream.end (/snapshot/dist/node_modules/through/index.js:74:5)
    at Socket.onend (_stream_readable.js:651:10)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
result                    →                          → result-v-868365a594-7df7c844b6-bpt2r error: code = Unknown desc = Error: No such container: 4c528a1c97d48734e6b996bad9cee748bbd388b08b6ef017e633c2a2fc03a0c8
```

It appears Garden doesn't reconnect to the right container.

**Comment by edvald** [comment]
@eysi09 was working on this, not sure if the recent fix relates.

**Comment by eysi09** [comment]
No this is still an issue. I don't think this is a regression, we've just never addressed this.
