### ISSUE TITLE
0.13: [UX]: Too heavy and awkward error message on template string error

### ISSUE THREAD

**Issue by vvagaytsev** [garden-io/garden#4305]
### Current Behavior

Currently, on 0.13 template string error messages look too huge and awkward:
```
✖ Invalid template string (${environment.namespace}): Could not find key environment. Available keys: command, datetime, git, local, project and secrets.

Error: Invalid template string (${environment.namespace}): Could not find key environment. Available keys: command, datetime, git, local, project and secrets.
    at resolveTemplateString (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:206:11)
    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:221:15)
    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20
    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:275:48)
    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20
    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:275:48)
    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20
    at resolveProjectConfig (/Users/vladimirvagaytsev/Repositories/garden/core/src/config/project.ts:453:46)
    at _resolveGardenParams (/Users/vladimirvagaytsev/Repositories/garden/core/src/garden.ts:1799:32)
    at Function.factory (/Users/vladimirvagaytsev/Repositories/garden/core/src/garden.ts:401:29)
    at GardenCli.runCommand (/Users/vladimirvagaytsev/Repositories/garden/core/src/cli/cli.ts:322:18)
    at GardenCli.run (/Users/vladimirvagaytsev/Repositories/garden/core/src/cli/cli.ts:558:26)
    at Object.runCli (/Users/vladimirvagaytsev/Repositories/garden/cli/src/cli.ts:42:14)

Error Details:

err:
  type: template-string
  message: "\e[31mCould not find key \e[37menvironment\e[39m\e[31m\e[39m\e[31m.\e[39m\e[31m Available keys: \e[37mcommand\e[39m\e[31m, \e[37mdatetime\e[39m\e[31m, \e[37mgit\e[39m\e[31m, \e[37mlocal\e[39m\e[31m, \e[37mproject\e[39m\e[31m and \e[37msecrets\e[39m\e[31m.\e[39m"
  stack: "Error: \e[31mCould not find key \e[37menvironment\e[39m\e[31m\e[39m\e[31m.\e[39m\e[31m Available keys: \e[37mcommand\e[39m\e[31m, \e[37mdatetime\e[39m\e[31m, \e[37mgit\e[39m\e[31m, \e[37mlocal\e[39m\e[31m, \e[37mproject\e[39m\e[31m and \e[37msecrets\e[39m\e[31m.\e[39m

    \    at peg$c6 (/Users/vladimirvagaytsev/Repositories/garden/core/build/src/template-string/parser.js:206:32)

    \    at peg$parseFormatString (/Users/vladimirvagaytsev/Repositories/garden/core/build/src/template-string/parser.js:891:22)

    \    at peg$parseTemplateString (/Users/vladimirvagaytsev/Repositories/garden/core/build/src/template-string/parser.js:693:10)

    \    at Object.peg$parse [as parse] (/Users/vladimirvagaytsev/Repositories/garden/core/build/src/template-string/parser.js:5445:16)

    \    at resolveTemplateString (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:98:27)

    \    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:221:15)

    \    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20

    \    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:275:48)

    \    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20

    \    at $resolveTemplateStrings (/Users/vladimirvagaytsev/Repositories/garden/core/src/template-string/template-string.ts:275:48)

    \    at /Users/vladimirvagaytsev/Repositories/garden/core/src/util/profiling.ts:196:20

    \    at resolveProjectConfig (/Users/vladimirvagaytsev/Repositories/garden/core/src/config/project.ts:453:46)

    \    at _resolveGardenParams (/Users/vladimirvagaytsev/Repositories/garden/core/src/garden.ts:1799:32)

    \    at Function.factory (/Users/vladimirvagaytsev/Repositories/garden/core/src/garden.ts:401:29)

    \    at GardenCli.runCommand (/Users/vladimirvagaytsev/Repositories/garden/core/src/cli/cli.ts:322:18)

    \    at GardenCli.run (/Users/vladimirvagaytsev/Repositories/garden/core/src/cli/cli.ts:558:26)

    \    at Object.runCli (/Users/vladimirvagaytsev/Repositories/garden/cli/src/cli.ts:42:14)"
  detail:
    text: ${environment.namespace}
```

### Expected behavior

In 0.12 it looks much more concise and readable:

```
Invalid template string (${environment.namespace}): Could not find key environment. Available keys: command, datetime, git, local, project and secrets.
```

### Reproducible example

Add an unsupported key in the variables config, e.g. add this to the project-level `garden.yml`:
```
variables:
  environmentNamespace: ${environment.namespace}
```
and run the `validate` command.

### Suggested solution(s)

Remove stack traces and any other unnecessary information from the output.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`

**Comment by thsig** [comment]
I'll take this one.
