### ISSUE TITLE
0.13: [Bug]: Terraform modules not exporting runtime.services.<module-name>.outputs

### ISSUE THREAD

**Issue by twelvemo** [garden-io/garden#4687]
`##` Garden Bonsai (0.13) Bug

### Current Behavior
When deploying a module that has references to a terraform module's output garden fails. This was working in 0.12 via the `runtime.services.<module-name>.outputs` key  [(see reference docs)](https://docs.garden.io/v/acorn-0.12/reference/module-types/terraform#usd-runtime.services.less-than-service-name-greater-than.outputs.). In the reference docs for 0.13 terraform deploy actions i can see that [references to terraform outputs exist for terraform deploy actions](https://docs.garden.io/reference/action-types/deploy/terraform#usd-actions.deploy.less-than-name-greater-than.outputs) and have have been removed for [terraform modules](https://docs.garden.io/reference/module-types/terraform#service-outputs). 

When running `garden deploy` in a garden project that includes a terraform module and another module that references the terraform module's output garden fails with:
```
Deploy type=kubernetes name=aws-auth (from module aws-auth) depends on one or more runtime outputs from action key() {
        return actionReferenceToString(this);
    }, which is disabled. Please either remove the reference or enable the action.
[silly] Error: Deploy type=kubernetes name=aws-auth (from module aws-auth) depends on one or more runtime outputs from action key() {
        return actionReferenceToString(this);
    }, which is disabled. Please either remove the reference or enable the action.
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/base.ts:263:17
    at Array.flatMap (<anonymous>)
    at wrapped.resolveProcessDependencies (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/base.ts:255:56)
    at wrapped.getProcessDependencies (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/tasks/base.ts:161:17)
    at wrapped.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/typescript-memoize/src/memoize-decorator.ts:111:36)
    at wrapped (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:154:39)
    at wrapped.getDependencies (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/nodes.ts:251:35)
    at wrapped (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:154:39)
    at wrapped.getRemainingDependencies (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/nodes.ts:78:17)
    at wrapped (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:154:39)
    at wrapped.loop (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/solver.ts:287:36)
    at wrapped (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/util/profiling.ts:154:39)
    at wrapped.<anonymous> (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/solver.ts:92:12)
    at wrapped.emit (/snapshot/project/tmp/pkg/cli/node_modules/eventemitter2/lib/eventemitter2.js:1011:19)
    at /snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/src/graph/solver.ts:341:18
```

### Expected behavior

Is the terraform plugin expected to work with modules in bonsai as well or should we add a notice to upgrade to deploy actions? If it is supposed to work, we would need to add the outputs again otherwise it is not possible to reference terraform outputs in other garden modules.

### Reproducible example

Happy to provide an example and more detail, if we have the intention of fixing this.

### Workaround

Use garden 0.12 with the modules.

### Your environment

* **OS:** 
* **How I'm running Kubernetes:**  

`garden version`
0.13.3

**Comment by Orzelius** [comment]
@twelvemo I started digging into this and found that module outputs work for both terraform and exec modules. If you ignore the javascript intrusion into the error message you'll see that it's actually stating that the action (that comes from the module conversion) you're trying to grab outputs from is disabled.

Fixed the broken error message rendering here: https://github.com/garden-io/garden/pull/4746/commits/3ba2c29ced637f28100112bbb1b5df856598e57f

**Comment by twelvemo** [comment]
@Orzelius nice, good catch and sorry for sending you on the wrong trail here. Didn't spot the part about the disabled module/action. 
If the module output works, why is it missing from the reference docs though? https://docs.garden.io/reference/module-types/terraform#service-outputs

**Comment by Orzelius** [comment]
> missing from the reference docs

I don't know to be honest. The `[ModuleTypeDefinition](https://github.com/garden-io/garden/blob/fixes/core/src/plugin/module-types.ts#L116)` type no longer has properties for task and service outputs so it seems that the logic was removed on purpose. I don't know how much value would working on adding that stuff back have as it's functioning right now and would be only a docs benefit to deprecated modules.

**Comment by Orzelius** [comment]
I'm closing this for now. Might reopen if we decide we want the docs after all
