### ISSUE TITLE
0.13: [Bug]: Failed to recognize state when pulumi identified no resources changed

### ISSUE THREAD

**Issue by ishantagarwal-x213235** [garden-io/garden#5084]
### Current Behavior

garden is failing to recognize the state when pulumi identified no resources available to change.

`Failed to Deploy type=pulumi name=x-service (from module x-service): Error: Deploy type=pulumi name=x-service (from module x-service) failed: TypeError: Cannot read properties of null (reading 'state')`

Command `garden plugins pulumi preview` 

### Expected behavior
garden should executed the command successfully without throwing an error.

Reference project
https://github.com/ishantagarwal-x213235/garden-sample-project

**Comment by ishantagarwal-x213235** [comment]
pick these lines from error logs that might help you

```
Failed to Deploy type=pulumi name=thx-dynatrace-infra (from module thx-dynatrace-infra): Error: Deploy type=pulumi name=thx-dynatrace-infra (from module thx-dynatrace-infra) failed: TypeError: Cannot read properties of null (reading 'state')
[silly] Error: Failed to Deploy type=pulumi name=thx-dynatrace-infra (from module thx-dynatrace-infra): Error: Deploy type=pulumi name=x-service (from module x-service) failed: TypeError: Cannot read properties of null (reading 'state')
    at RequestTaskNode.completeHandler (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/solver.js:93:36)
    at RequestTaskNode.complete (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/nodes.js:165:14)
    at ProcessTaskNode.complete (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/nodes.js:112:19)
    at GraphSolver.completeTask (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/solver.js:356:29)
    at GraphSolver.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/solver.js:283:27)

Error Details:
```

**Comment by shumailxyz** [comment]
Probably same as https://github.com/garden-io/garden/issues/5118

**Comment by ishantagarwal-x213235** [comment]
yes, it's the same issue
