### ISSUE TITLE
Crash: toKubernetesError encountered an unknown error unexpectedly during Kub

### ISSUE THREAD

**Issue by bulliana** [garden-io/garden#5097]
## Crash report
`garden deploy` crashed for `deploy.api` and `deploy.version-check`

### Error message

```
✖ deploy.api           → Failed resolving status for Deploy type=kubernetes name=api (from module api) (took 17.69 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20toKubernetesError%20encountered%20an%20unknown%20error%20unexpectedly%20during%20Kub...

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed resolving status for Deploy type=kubernetes name=api (from module api) (took 17.69 sec). This is what happened:
RequestError: Error: connect ETIMEDOUT 18.194.93.210:443
    at new RequestError (/snapshot/project/tmp/pkg/cli/node_modules/request-promise-core/lib/errors.js:14:15)
    at plumbing.callback (/snapshot/project/tmp/pkg/cli/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/snapshot/project/tmp/pkg/cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/snapshot/project/tmp/pkg/cli/node_modules/request/request.js:185:22)
    at Request.emit (node:events:537:28)
    at Request.emit (node:domain:482:12)
    at Request.onRequestError (/snapshot/project/tmp/pkg/cli/node_modules/request/request.js:877:8)
    at /snapshot/project/tmp/pkg/cli/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55
    at AsyncLocalStorage.run (node:async_hooks:330:14)
    at AsyncLocalStorageContextManager.with (/snapshot/project/tmp/pkg/cli/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ClientRequest.contextWrapper (/snapshot/project/tmp/pkg/cli/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)
    at ClientRequest.emit (node:events:537:28)
    at ClientRequest.emit (node:domain:482:12)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at TLSSocket.emit (node:domain:482:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: /api/v1/namespaces/ge-ulianasirotina/serviceaccounts/api-serviceaccount: toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: /api/v1/namespaces/ge-ulianasirotina/serviceaccounts/api-serviceaccount: Error: connect ETIMEDOUT 18.194.93.210:443

```

### What did you do?

```
garden delete environment
garden deploy
```

### Your environment

* **OS:** macOS 13.5.2 
* **How I'm running Kubernetes:** 🤷‍♀️
* **Garden version:** garden version: 0.13.13-edge-bonsai-1f585c672

### Frequency

Keeps happening 

### Workaround

```
garden deploy --force
```

**Comment by stefreak** [comment]
This should not be rendered as a bug

We fixed this in #5092
