### ISSUE TITLE
Crash: Cannot read properties of null (reading 'state')

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5118]
### Error message

```console
$ garden --env=dev plugins pulumi preview
Plugins 

Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ garden               → Running in Garden environment dev.garden-dev-salotz
Running pulumi preview for actions  

ℹ providers            → Getting status...
✔ providers            → Cached (took 0 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ providers            → Getting status...
✔ providers            → Cached (took 0 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 2.2 sec)

ℹ deploy.test-data-sa  → Running pulumi preview
ℹ deploy.test-data-sa  → No resources were changed in the generated plan for deploy.test-data-sa.
✔ deploy.test-data-sa  → Success (took 7.7 sec)
✖ deploy.test-data-sa  → Failed processing Deploy type=pulumi name=test-data-sa (took 7.7 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20Cannot%20read%20properties%20of%20null%20(reading%20%27state%27)

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed processing Deploy type=pulumi name=test-data-sa (took 7.7 sec). This is what happened:
TypeError: Cannot read properties of null (reading 'state')
    at ProcessTaskNode.execute (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/nodes.js:214:31)
    at async GraphSolver.processNode (/snapshot/project/tmp/pkg/cli/node_modules/@garden-io/core/build/src/graph/solver.js:282:35)
──────────────────────────────────────────────────────────────────────────────────────────────────────────
Failed to Deploy type=pulumi name=test-data-sa: Error: Deploy type=pulumi name=test-data-sa failed: Error: Cannot read properties of null (reading 'state')
```

### Your environment

* **OS: linux** 
* **How I'm running Kubernetes: GKE** 
* **Garden version: garden version: 0.13.14** 

### Frequency

It happens every time I run the command.

### Workaround

I don't really need this command so not a big deal.

**Comment by shumailxyz** [comment]
@salotz  Thanks for reporting this and using the crash issue template 👍 We'll take a look.
