### ISSUE TITLE
garden logs tail: unexpected token

### ISSUE THREAD

**Issue by adnaan** [garden-io/garden#514]
## Bug
`garden logs -t mysvc` fails to execute
### Current Behavior

```
garden logs -t mysvc

mysvc                       → 2019-02-05T07:37:49.578Z →
mysvc                       → 2019-02-05T07:37:49.578Z → U  /"\  u       ___      U |  _"\ u
undefined:1
{"message":"2019-02-05T07:37:50.1294313Z /entrypoint.sh: ignoring /docker-entrypoint.d/*\n","namespace":"garden--default--myprj","podName":"mysvc-57f657dffd-zq5mr","containerName":"garden-rsync"}{"message":"2019-02-05T07:37:49.5782618Z  \\\\    \u003e\u003e  .-,_|___|_,-.   //   \\\\_\n","namespace":"garden--default--myprj","podName":"mysvc-57f657dffd-zq5mr","containerName":"mysvc"}
                                                                                                                                                                                                  ^

SyntaxError: Unexpected token { in JSON at position 194
    at JSON.parse (<anonymous>)
    at Stream.proc.stdout.pipe.on (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/build/plugins/kubernetes/logs.js:67:30)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at drain (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/through/index.js:45:5)
    at emit (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/split/index.js:37:14)
    at next (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/split/index.js:54:5)
    at Stream.stream.write (/usr/local/Cellar/garden-cli/0.8.1/libexec/lib/node_modules/garden-cli/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
```

### Suggested solution(s)

The culprit seems to be : https://github.com/garden-io/garden/blob/v0.8.1/garden-service/src/plugins/kubernetes/logs.ts#L69

The incoming line is: 
```
{
	"message": "2019-02-05T07:37:50.1294313Z /entrypoint.sh: ignoring /docker-entrypoint.d/*\n",
	"namespace": "garden--default--myprj",
	"podName": "mysvc-57f657dffd-zq5mr",
	"containerName": "garden-rsync"
} {
	"message": "2019-02-05T07:37:49.5782618Z  \\\\    \u003e\u003e  .-,_|___|_,-.   //   \\\\_\n",
	"namespace": "garden--default--myprj",
	"podName": "mysvc-57f657dffd-zq5mr",
	"containerName": "mysvc"
}
```

Before parsing we should split the line by delimiter `}` and parse the resultant lines.

### Your environment

OSX High Sierra 10.13.15
```
garden --version
0.8.1
```

```
 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
```
docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by eysi09** [comment]
Thanks for catching this one!

Here's how to reproduce it using the `vote-helm`  example:

1. In the `vote-helm` example, run `garden dev --hot-reload=vote`
2. In the `vote-helm` example in a different console window, run: `garden logs --follow`
3. Open http://vote.local.app.garden/ in a browser window.
4. Vote for Cats (obviously).
5. Notice that the `garden logs --follow` process has crashed with the error below.

Error:

```sh
undefined:1
{"message":"2019-02-06T10:32:08.2564787Z /entrypoint.sh: ignoring /docker-entrypoint.d/*\n","namespace":"vote-helm","podName":"vote-55b788bf56-42dpv","containerName":"garden-rsync"}{"message":"2019-02-06T10:32:08.3441125Z \u003e vue-cli-service serve --dashboard\n","namespace":"vote-helm","podName":"vote-55b788bf56-42dpv","containerName":"vote"}
                                                                                                                                                                                     ^

SyntaxError: Unexpected token { in JSON at position 181
    at JSON.parse (<anonymous>)
    at Stream.proc.stdout.pipe.on (/snapshot/project/garden-service/tmp/dist/build/plugins/kubernetes/logs.js:57:30)
    at Stream.emit (events.js:182:13)
    at drain (/snapshot/project/garden-service/tmp/dist/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/snapshot/project/garden-service/tmp/dist/node_modules/through/index.js:45:5)
    at emit (/snapshot/project/garden-service/tmp/dist/node_modules/split/index.js:37:14)
    at next (/snapshot/project/garden-service/tmp/dist/node_modules/split/index.js:49:7)
    at Stream.<anonymous> (/snapshot/project/garden-service/tmp/dist/node_modules/split/index.js:54:5)
    at Stream.stream.write (/snapshot/project/garden-service/tmp/dist/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:663:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:635:20)
```
