### ISSUE TITLE
0.13: [Bug]: Garden crashes if kubernetes auth command fails

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5419]
### Current Behavior

```
✖ deploy.workflow-runner-rbac → Failed resolving status for Deploy type=kubernetes name=workflow-runner-rbac (from module workflow-runner-rbac) (took 7 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20toKubernetesError%20encountered%20an%20unknown%20error%20unexpectedly%20during%20Kub...

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed resolving status for Deploy type=kubernetes name=workflow-runner-rbac (from module workflow-runner-rbac) (took 7 sec). This is what happened:
Error:
The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.

    at ExecAuth.getCredential (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:525083:16)
    at ExecAuth.applyAuthentication (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:525021:34)
    at KubeConfig.applyAuthorizationHeader (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:675931:34)
    at KubeConfig.applyOptions (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:675939:21)
    at KubeConfig.applyToHTTPSOptions (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:675600:21)
    at KubeConfig.applyToFetchOptions (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:675576:21)
    at file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:739810:52
    at retry (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:692360:26)
    at requestWithRetry (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:692386:26)
    at KubeApi.request (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1699599691-L61ezMb.r/rollup/garden.mjs:739804:22)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: https://89026221a372d5452a397ffaae3e191b.gr7.eu-central-1.eks.amazonaws.com/api/v1/namespaces/ge-steffen/configmaps/garden-meta-deploy-workflow-runner-rbac:
The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.
```

### Expected behavior

```
✖ deploy.workflow-runner-rbac → Failed resolving status for Deploy type=kubernetes name=workflow-runner-rbac (from module workflow-runner-rbac) (took 7 sec). This is what happened:

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Kubernetes authentication failed: The SSO session associated with this profile has expired or is otherwise invalid. To refresh this SSO session run aws sso login with the corresponding profile.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```
### Reproducible example

garden-platform
1. Start a garden dev session
2. Wait for 24 hours
3. Run garden deploy --sync

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` edge-bonsai

**Comment by stefreak** [comment]
Dup #6378
