### ISSUE TITLE
Crash: GraphError: SYNCHRONOUS TERMINATION NOTICE

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5445]
### Error message

When referencing a dependency that does not exist, Garden crashes with `SYNCHRONOUS TERMINATION NOTICE`:
```
✖ test.foo             → An internal error occurred while resolving status for resolve Test type=exec name=foo. This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Could not find Deploy action foo.

Declared action names for action kind 'Deploy': <None>
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
SYNCHRONOUS TERMINATION NOTICE: When explicitly exiting the process via process.exit or via a parent process, asynchronous tasks in your exitHooks will not run. Either remove these tasks, use gracefulExit() instead of process.exit(), or ensure your parent process sends a SIGINT to the process running this code.
Waiting for the debugger to disconnect...
file:///Users/steffen/work/github/garden/core/build/src/graph/config-graph.js:91
            throw new GraphError({
                  ^

GraphError: Could not find Deploy action foo.

Declared action names for action kind 'Deploy': <None>
    at MutableConfigGraph.getActionByKind (file:///Users/steffen/work/github/garden/core/build/src/graph/config-graph.js:91:19)
    at MutableConfigGraph.getActionByRef (file:///Users/steffen/work/github/garden/core/build/src/graph/config-graph.js:86:21)
    at file:///Users/steffen/work/github/garden/core/build/src/actions/base.js:387:39
    at Array.forEach (<anonymous>)
    at TestAction.getFullVersion (file:///Users/steffen/work/github/garden/core/build/src/actions/base.js:386:27)
    at TestAction.<anonymous> (/Users/steffen/work/github/garden/core/node_modules/typescript-memoize/dist/memoize-decorator.js:132:52)
    at TestAction.versionString (file:///Users/steffen/work/github/garden/core/build/src/actions/base.js:432:21)
    at ResolveActionTask.getInputVersion (file:///Users/steffen/work/github/garden/core/build/src/tasks/base.js:120:28)
    at StatusTaskNode.complete (file:///Users/steffen/work/github/garden/core/build/src/graph/nodes.js:84:35)
    at file:///Users/steffen/work/github/garden/core/build/src/graph/solver.js:264:26 {
  taskType: undefined,
  code: undefined,
  wrappedErrors: undefined,
  unexpandedStack: undefined,
  type: 'graph'
}

Node.js v21.1.0
```

### What did you do?

Command: `garden test`

```
# garden.yml
apiVersion: garden.io/v1
kind: Project
name: foo
environments:
  - name: local

---

kind: Test
type: exec
name: foo
dependencies:
 - deploy.foo

```

### Your environment

* **OS:** macOS
* **Garden version:** 0.13.20

### Frequency

Reproducable

**Comment by thsig** [comment]
Closed by #5732.
