### ISSUE TITLE
0.13: [Bug]: Misleading template error on "git dubious ownership" error

### ISSUE THREAD

**Issue by stefreak** [garden-io/garden#5450]
### Current Behavior

```
[verbose] garden version: 0.13.20
Validate ✔️

ℹ garden-enterprise [debug] → Initializing Garden Cloud API client.
[silly] Retrieving client auth token from config store
[debug] Checking client auth token with Garden Enterprise: https://staging.enterprise.garden.io/token/verify
[silly] Calling Cloud API with GET token/verify
[silly] Retrieving client auth token from config store
[debug] Checked client auth token with Garden Enterprise - valid: true
ℹ garden-enterprise [debug] → Authorizing...
ℹ garden-enterprise [debug] → Starting refresh interval.
[debug] Will run refresh function every 4500 ms.
[silly] Calling git with args 'rev-parse --abbrev-ref HEAD' in /Users/steffen/work/github/garden-platform
[silly] Calling git with args 'config --get remote.origin.url' in /Users/steffen/work/github/garden-platform
[silly] Tried to retrieve git remote.origin.url but encountered an error: Error: Command "git config --get remote.origin.url" failed with code 1:
ℹ garden-enterprise [verbose] → Connecting to Garden Enterprise...
ℹ garden-enterprise [debug] → Fetching project ccf57c5e-35eb-4e73-9f5a-0327f9e528e5 from https://staging.enterprise.garden.io.
[silly] Calling Cloud API with GET /projects/uid/ccf57c5e-35eb-4e73-9f5a-0327f9e528e5
[silly] Retrieving client auth token from config store
[silly] Calling Cloud API with GET /secrets/projectUid/ccf57c5e-35eb-4e73-9f5a-0327f9e528e5/env/dev
[silly] Retrieving client auth token from config store
ℹ garden-enterprise [debug] → Fetched 33 secrets from https://staging.enterprise.garden.io
✔ garden-enterprise    → Ready
Failed to resolve project configuration.
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Invalid template string (ge-preview-${slice(local.env.GARDE…): Error validating argument 'input' for slice helper function:
value is not allowed to be empty
[silly] Error: Invalid template string (ge-preview-${slice(local.env.GARDE…): Error validating argument 'input' for slice helper function:
value is not allowed to be empty
    at resolveTemplateString (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:321985:15)
    at resolveTemplateStrings (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:322004:16)
    at resolveTemplateStrings (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:322065:34)
    at resolveTemplateStrings (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:322065:34)
    at resolveProjectConfig (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:353470:24)
    at file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:819731:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:358410:20
    at async Garden.factory (file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:818606:33)
    at async file:///Users/steffen/Library/Application%20Support/io.garden.garden/1700246687-AJiCnyg.r/rollup/garden.mjs:358410:20
Error type: template-string
```

### Expected behavior

```
Command "git rev-parse --show-toplevel" failed with code 128:

     fatal: detected dubious ownership in repository at '/Users/steffen/work/github/garden-platform'
To add an exception for this directory, call:

	git config --global --add safe.directory /Users/steffen/work/github/garden-platform
```

### Reproducible example

1. `cd garden-platform` (internal project)
2. `sudo chown nobody:nobody .`
3. `garden validate`

### Workaround

Run `git status` to see what's wrong, and fix the issue with `git`.

### Suggested solution(s)

Make sure we do not swallow the git error

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS

`garden version` latest edge release

**Comment by stefreak** [comment]
This part wasn't fixed in #5434 / #5439 so I extracted it as a separate open issue.

**Comment by stefreak** [comment]
With #6745 the error is a little bit easier to understand now at least;

I assume that branch name is empty as it failed to run the git command?

```
Failed to resolve project configuration.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/Users/steffen/work/github/garden-platform/project.garden.yml:113
...
112  |   e2eEnvName: ge-e2e-${local.env.GARDEN_RUN_NUMBER && "${slice(kebabCase(git.branch),0,10)}-${slice(sha256(git.branch),0,5)}" || local.username}
113  |   previewEnvName: ge-preview-${slice(local.env.GARDEN_REPO_BRANCH || git.branch, 0, 13)}
-------------------------^
Error validating argument 'input' for slice helper function:

value is not allowed to be empty
```

**Comment by stefreak** [comment]
The root cause is probably the `git.branch` is simply empty when the git ownership is dubious
