### ISSUE TITLE
Crash: toKubernetesError encountered an unknown error unexpectedly during Kub

### ISSUE THREAD

**Issue by worldofgeese** [garden-io/garden#5529]
### Error message

```console
Failed resolving status for Build type=container name=worker (took 2.09 sec). This is what happened:
Error: Cannot parse content. No Content-Type defined.
    at ObjectSerializer.parse (file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:567762:21)
    at CoreV1ApiResponseProcessor.readNamespacedPodLogWithHttpInfo (file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:601871:111)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retry (file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:698396:20)
    at async requestWithRetry (file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:698422:20)
    at async file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:702239:19
    at async Promise.all (index 1)
    at async file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:702302:25
    at async Promise.all (index 0)
    at async getFormattedPodLogs (file:///home/worldofgeese/.local/share/garden/1701105295-4FRYmZ4.r/rollup/garden.mjs:702297:21)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: readNamespacedPodLog: toKubernetesError encountered an unknown error unexpectedly during readNamespacedPodLog: Cannot parse content. No Content-Type defined.
```

### What did you do?

On 0.13.20 and 0.13.21, both `garden deploy` and `garden build` error with the above output.
### Your environment

* **OS:** Ubuntu on WSL2
* **How I'm running Kubernetes:** EKS
* **Garden version:** `0.13.20` *and* `0.13.21`

### Frequency

Every invocation. 

### Workaround

Downgrade to 0.13.19.

**Comment by twelvemo** [comment]
Neither @worldofgeese nor I can reproduce this issue today, closing for now. We can reopen when it happens again.
