### ISSUE TITLE
Crash: toKubernetesError encountered an unknown error unexpectedly during Kub

### ISSUE THREAD

**Issue by salotz** [garden-io/garden#5789]
### Error message

```
× deploy.rclone-copier      → Failed processing Deploy type=kubernetes name=rclone-copier (took 5.39 sec). This is what happened:

──────────────────────────────────────────────────────────────────────────────────────────────────────────
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20toKubernetesError%20encountered%20an%20unknown%20error%20unexpectedly%20during%20Kub...

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed processing Deploy type=kubernetes name=rclone-copier (took 5.39 sec). This is what happened:
Error: Cannot parse content. No Content-Type defined.
    at ObjectSerializer.parse (file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:571760:21)
    at CoreV1ApiResponseProcessor.readNamespacedPodLogWithHttpInfo (file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:605869:111)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async retry (file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:702394:20)
    at async requestWithRetry (file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:702420:20)
    at async file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:706237:19
    at async Promise.all (index 0)
    at async file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:706300:25
    at async Promise.all (index 0)
    at async getFormattedPodLogs (file:///home/salotz/.local/share/garden/1704389917-mmwDKlV.r/rollup/garden.mjs:706295:21)
──────────────────────────────────────────────────────────────────────────────────────────────────────────

toKubernetesError encountered an unknown error unexpectedly during Kubernetes API: readNamespacedPodLog: toKubernetesError encountered an unknown error unexpectedly during readNamespacedPodLog: Cannot parse content. No Content-Type defined.
[debug] Done flushing all events and log entries.
```
### What did you do?

```
garden -l4 --env=dev --force-refresh test functional-tests
```

I had previously run this deploy which failed because it was waiting for a ConfigMap volume that did not exist. I fixed this and then tried to redeploy without cleaning up the previous deploy.

### Your environment

* **OS:** linx, openSUSE Tumbleweed
* **How I'm running Kubernetes:** GKE
* **Garden version:** `garden version: 0.13.23`

### Frequency

I haven't reproduced, although I haven't tried very hard.

### Workaround

I just cleaned things up on the cluster manually and the issue went away.

### Additional context

None

**Comment by 10ko** [comment]
Hi @salotz, we believe we fixed this issue with #5690, could you perhaps try with a newer Garden version?

**Comment by 10ko** [comment]
I am going to close this, feel free to reopen if the error persist.

**Comment by salotz** [comment]
I updated. If I get it again I will let you know.
