### ISSUE TITLE
Garden 0.13 crashes if K8s token expired

### ISSUE THREAD

**Issue by bxsx** [garden-io/garden#6378]
### Error message

```
Encountered an unexpected Garden error. This is likely a bug 🍂

You can help by reporting this on GitHub: https://github.com/garden-io/garden/issues/new?labels=bug,crash&template=CRASH.md&title=Crash%3A%20toKubernetesError%20encountered%20an%20unknown%20error%20during%20Kubernetes%20API%3A%20...

Please attach the following information to the bug report after making sure that the error message does not contain sensitive information:

Failed resolving status for Test type=container name=my-image-test (from module my-image) (took 5.31 sec). This is what happened:
Error:
Error when retrieving token from sso: Token has expired and refresh failed

    at ExecAuth.getCredential (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:541288:16)
    at ExecAuth.applyAuthentication (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:541223:34)
    at KubeConfig.applyAuthorizationHeader (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:707815:34)
    at KubeConfig.applyOptions (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:707823:21)
    at KubeConfig.applySecurityAuthentication (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:707517:21)
    at CoreV1ApiRequestFactory.readNamespace (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:615587:91)
    at ObservableCoreV1Api.readNamespaceWithHttpInfo (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:669702:60)
    at ObservableCoreV1Api.readNamespace (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:669723:22)
    at ObjectCoreV1Api.readNamespace (file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:690858:26)
    at file:///Users/bart/Library/Application%20Support/io.garden.garden/1723489547-dMYvoI9.r/rollup/garden.mjs:761500:52
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

toKubernetesError encountered an unknown error during Kubernetes API: readNamespace: toKubernetesError encountered an unknown error during readNamespace:
Error when retrieving token from sso: Token has expired and refresh failed
2 requested test action(s) failed!
```

### What did you do?

`garden test`

### Your environment

* **OS:** macOS
* **How I'm running Kubernetes:** EKS
* **Garden version:** 0.13.37

### Frequency

This crash is reproducible, just make sure your token expired.

### Workaround

`aws sso login`

**Comment by stefreak** [comment]
Thank you for reporting this!
