### ISSUE TITLE
Unhandled error when specifying missing service with --hot flag

### ISSUE THREAD

**Issue by edvald** [garden-io/garden#653]
### Current Behavior

`garden dev --hot=fooooo`

```
(node:14954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:14954) UnhandledPromiseRejectionWarning: Error: Could not find service(s): fooooo
     at Object.pickKeys (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/util/util.js:430:15)
     at ConfigGraph.<anonymous> (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/config-graph.js:186:58)
     at Generator.next (<anonymous>)
     at /Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/config-graph.js:14:71
     at new Promise (<anonymous>)
     at __awaiter (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/config-graph.js:10:12)
     at ConfigGraph.getServices (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/config-graph.js:185:16)
     at DevCommand.<anonymous> (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/commands/dev.js:87:70)
     at Generator.next (<anonymous>)
     at /Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/commands/dev.js:14:71
     at new Promise (<anonymous>)
     at __awaiter (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/commands/dev.js:10:12)
     at /Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/commands/dev.js:84:50
     at Object.<anonymous> (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/process.js:121:41)
     at Generator.next (<anonymous>)
     at /Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/process.js:14:71
     at new Promise (<anonymous>)
     at __awaiter (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/process.js:10:12)
     at Bluebird.map (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/build/process.js:119:59)
     at tryCatcher (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/node_modules/bluebird/js/release/util.js:16:23)
     at MappingPromiseArray._promiseFulfilled (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/node_modules/bluebir
d/js/release/map.js:61:38)
     at MappingPromiseArray.PromiseArray._iterate (/Users/edvald/golang/src/github.com/garden-io/garden/garden-service/node_modules/blu
```

### Expected behavior

Throw error on startup because the service doesn't exist.

### Reproducible example

Run `garden dev --hot=ojeorihgerlighergohierlgihergeir` in any project.

### Suggested solution(s)

Need to both track down where we're not handling the promise rejection, and validate the input as well to reject it immediately.

### Your environment

Latest master.

**Comment by eysi09** [comment]
There's already an issue for this: #599

**Comment by edvald** [comment]
Ah, sorry. Missed that.
