### ISSUE TITLE
Unhandled error when reloading config with hot reloading enabled and a fixed port

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#654]
## Bug

Garden throws an unhandled error if a `garden.yml` configuration file is changed while running `garden dev` with a fixed port and hot reloading enabled.

### Current Behavior

Garden errors with:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1290:14)
    at listenInCluster (net.js:1338:12)
    at Server.listen (net.js:1425:7)
    at Application.listen (/Users/eysi/code/garden-io/garden/garden-service/node_modules/koa/lib/application.js:65:19)
    at Application.listen (/Users/eysi/code/garden-io/garden/garden-service/node_modules/koa-websocket/index.js:49:30)
    at Object.<anonymous> (/Users/eysi/code/garden-io/garden/garden-service/build/server/server.js:48:28)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/eysi/code/garden-io/garden/garden-service/build/server/server.js:11:58)
Emitted 'error' event at:
    at Server.emit (events.js:182:13)
    at emitErrorNT (net.js:1317:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Expected behavior

Should not error.

### Reproducible example

Go to `hot-reload` example and run:

```
GARDEN_SERVER_PORT=9000 garden dev --hot node-service
```

Then change a `garden.yml` configuration file.

### Suggested solution(s)

N/A

### Additional context

N/A

### Your environment

Latest master.

**Comment by thsig** [comment]
Looks like this was fixed by https://github.com/garden-io/garden/pull/745.
