### ISSUE TITLE
Tasks example project fails intermittently when deployed to a remote cluster 

### ISSUE THREAD

**Issue by eysi09** [garden-io/garden#849]
The `node-migration` task in module `hello` fails intermittently because `Knex` times out. We use this project as a part of our integration test suite but it's configured to `skip` now because of this issue.

Here's the error message:

```
Failed running task node-migration in module hello. Here is the output:
————————————————————————————————————————————————————————————————————————————————
Command failed with code 1: /Users/eysi/.garden/tools/kubectl/52606cbad4c7babc/kubectl --context=gke_garden-dev-200012_europe-west1-b_garden-dev-1 --namespace=tasks-testing-1559712216442 run run-hello-1559712319717 --image=127.0.0.1:5000/tasks-testing-1559712216442/hello:v-dfeb9dfeaf --restart=Never --command --quiet --rm -i --overrides {"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}}} --env=GARDEN_VERSION=v-dfeb9dfeaf --env=GARDEN_MODULE_POSTGRES__DEPLOYMENT-IMAGE-NAME=127.0.0.1:5000/tasks-testing-1559712216442/postgres -- /bin/sh -c knex migrate:latest

TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /app/node_modules/knex/lib/client.js:339:13
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at /app/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
pod tasks-testing-1559712216442/run-hello-1559712319717 terminated (Error)

Here are the last 100 lines of the output:
————————————————————————————————————————————————————————————————————————————————
```

**Comment by edvald** [comment]
Is this still an issue?

**Comment by eysi09** [comment]
This was resolved by setting a timeout.
